"""``kortravelmap.infra`` — DB 어댑터 + 객체 저장소 + sync state.

``infra/``는 SQLAlchemy 2 async + GeoAlchemy2 + asyncpg + raw SQL (`sqlalchemy.
text()`)을 사용한다. ORM 모델은 매핑만 — 모든 쿼리는 `infra/*_repo.py`의
raw SQL (ADR-004).

**Sprint 1 PR#21 (본 PR)**:
- ``crs.py`` — ``pyproj.Transformer`` singleton (ADR-030 narrow cache,
  ``transformer_4326_to_5179`` / ``transformer_5179_to_4326``).
- ``db.py`` — async engine + session factory (``make_async_engine`` /
  ``make_async_session_factory`` / ``normalize_async_dsn``).
- ``tests/integration/conftest.py`` — testcontainers PostGIS fixture base
  (``pg_container`` / ``pg_engine`` / ``pg_session`` / ``feature_schema``).

**Sprint 2 첫 provider 적재 직전 PR**:
- ``models.py`` — SQLAlchemy 2 매핑 (``Feature``/``PlaceDetail``/...)
- ``feature_repo.py`` — raw SQL repository (``_SQL`` 상수 + ``text()``)
- ``source_repo.py``/``sync_repo.py``/``jobs_repo.py``
- ``scope_repo.py``/``feature_update_repo.py`` — ADR-045 feature update request 해석/큐
- ``file_store.py`` — S3 호환 객체 저장소 (RustFS)

ADR 참조
--------
- ADR-002 — async-only (SQLAlchemy 2 async + asyncpg)
- ADR-004 — ORM 매핑만, 쿼리는 raw SQL (EXPLAIN 친화 + 인덱스 hint 자유)
- ADR-007 — PostgreSQL 16 + PostGIS 3.5 + pg_trgm + pgcrypto
- ADR-008 — extension은 ``x_extension`` schema에 격리
- ADR-011 — 작업 큐 ``ops.import_jobs`` 영속화 + advisory lock + SKIP LOCKED
- ADR-012 — 공간 쿼리 입력 좌표 1회 변환, 반경은 ``coord_5179`` (meter)
- ADR-013 — bulk insert ``psycopg.copy_*`` 우선, 30k 안전 마진
- ADR-015 — 객체 저장소 S3 호환 (RustFS 1차, MinIO/Ceph/R2 swap)
- ADR-030 — ``functools.cache`` narrow 예외 (``pyproj.Transformer`` singleton)
"""

from __future__ import annotations

from kortravelmap.infra.admin_feature_repo import (
    AdminFeaturePage,
    AdminFeatureRow,
    AdminFeatureStateConflict,
    AdminFeatureStateNotFound,
    AdminFeatureStatePreconditionFailed,
    AdminFeatureStateTransition,
    AdminFeatureStateTransitionAudit,
    AdminFeatureStateTransitionAuditPage,
    AdminFeatureStateValidationError,
    DedupReviewPage,
    DedupReviewRow,
    FeatureOverride,
    list_admin_feature_state_transitions,
    list_admin_features,
    list_dedup_reviews,
    merge_dedup_review,
    reactivate_admin_feature_state,
    set_dedup_review_decision,
    transition_admin_feature_state,
)
from kortravelmap.infra.advisory_lock import (
    advisory_lock,
    advisory_lock_key,
    try_advisory_lock,
)
from kortravelmap.infra.cache_target_event_repo import (
    CacheTargetRefreshMember,
    CacheTargetResultEvent,
    append_cache_target_links_reconciled_events,
    append_cache_target_refresh_status_events,
    capture_cache_target_refresh_members,
    capture_cache_target_refresh_members_by_keys,
    lock_cache_target_result_streams,
)
from kortravelmap.infra.cache_target_outbox_repo import (
    CacheTargetAppliedReceipt,
    CacheTargetClaimAckResult,
    CacheTargetDeadLetter,
    CacheTargetDeadLetterPage,
    CacheTargetDeliveryResult,
    CacheTargetEventClaim,
    CacheTargetOutboxEvent,
    ack_cache_target_events,
    cache_target_dead_letter_entity_tag,
    cache_target_event_cursor,
    claim_cache_target_events,
    get_cache_target_dead_letter,
    list_cache_target_dead_letters,
    nack_cache_target_event,
    parse_cache_target_event_cursor,
    replay_cache_target_dead_letter,
)
from kortravelmap.infra.cache_target_reconciliation_repo import (
    CacheTargetActiveReconciliation,
    CacheTargetOperation,
    CacheTargetReconciliationRecord,
    CacheTargetReconciliationResult,
    CacheTargetSnapshotGcBacklog,
    CacheTargetSnapshotGcBatchResult,
    CacheTargetSnapshotItem,
    CacheTargetSnapshotPage,
    CacheTargetSnapshotStatus,
    CacheTargetStreamDiscovery,
    CacheTargetStreamStatus,
    CacheTargetStreamStatusPage,
    begin_cache_target_reconciliation,
    cache_target_reconciliation_entity_tag,
    complete_cache_target_reconciliation,
    get_cache_target_operation,
    get_cache_target_reconciliation,
    get_cache_target_reconciliation_snapshot,
    get_cache_target_snapshot,
    get_cache_target_stream_discovery,
    list_cache_target_stream_statuses,
    observe_expired_cache_target_snapshot_backlog,
    prune_expired_cache_target_snapshots_batch,
    request_cache_target_reconciliation,
    seal_cache_target_reconciliation,
)
from kortravelmap.infra.cache_target_restore import (
    CacheTargetRestoreReference,
    fence_restored_cache_target_streams,
    list_cache_target_restore_references,
)
from kortravelmap.infra.cache_target_service_repo import (
    CacheTargetRefreshRequestResult,
    CacheTargetSourceRecord,
    create_cache_target_refresh_request,
    get_cache_target_refresh_request,
    get_cache_target_source,
)
from kortravelmap.infra.cache_target_stream_repo import (
    CacheTargetRestoreFenceResult,
    CacheTargetSourceApplyResult,
    CacheTargetStreamConflict,
    CacheTargetStreamControl,
    advance_cache_target_restore_fence,
    apply_cache_target_source,
    cache_target_stream_entity_tag,
    get_cache_target_stream,
    lock_cache_target_stream,
)
from kortravelmap.infra.crs import (
    EPSG_UTM_K,
    EPSG_WGS84,
    project_to_4326,
    project_to_5179,
    transformer_4326_to_5179,
    transformer_5179_to_4326,
)
from kortravelmap.infra.db import (
    make_async_engine,
    make_async_session_factory,
    normalize_async_dsn,
)
from kortravelmap.infra.dedup_refresh_repo import (
    DEDUP_REFRESH_DEFAULT_LIMIT,
    DedupRefreshFeature,
    DedupRefreshScope,
    list_dedup_refresh_features,
)
from kortravelmap.infra.dedup_repo import (
    DedupQueueResult,
    enqueue_dedup_candidate,
    enqueue_dedup_candidates,
    pending_dedup_reviews,
)
from kortravelmap.infra.feature_identity import (
    FeatureIdentity,
    FeatureIdentityInvariantError,
    FeatureIdentityRefError,
    count_features_missing_identity,
    get_feature_uuid_map,
    resolve_feature_identity,
)
from kortravelmap.infra.feature_operation_repo import (
    append_dagster_feature_attempt_event,
    ensure_dagster_feature_operation,
    finish_dagster_feature_membership,
    list_feature_operation_memberships,
    list_reconcilable_dagster_feature_runs,
    reconcile_dagster_feature_run,
    record_feature_operation_invariant_conflict,
)
from kortravelmap.infra.feature_repo import (
    FeatureLoadResult,
    FeatureSearchPage,
    FeatureSearchRow,
    NearbyFeaturePage,
    NearbyFeatureRow,
    features_in_bbox,
    features_nearby_poi_cache_target,
    get_feature_row,
    get_feature_rows_by_ids,
    get_public_feature_row,
    get_public_feature_rows_by_ids,
    list_active_place_coords,
    load_bundle,
    load_bundles,
    search_features,
    retire_features_absent_from_snapshot,
    retire_features_by_source_entity_ids,
    retire_geometryless_area_features_by_source,
    upsert_feature,
    upsert_source_link,
    upsert_source_record,
)
from kortravelmap.infra.feature_update_active_repo import (
    FeatureUpdateDispatchConflict,
    find_active_provider_dataset_request,
    is_active_provider_dataset_unique_violation,
    request_feature_update_dispatch,
)
from kortravelmap.infra.feature_update_executor import (
    FeatureUpdateExecutionPlan,
    FeatureUpdateExecutionResult,
    ProviderDatasetRefreshResult,
    ProviderDatasetRefreshRunner,
    ProviderDatasetRefreshScope,
    SkippedProviderDatasetRefresh,
    build_feature_update_execution_plan,
    execute_feature_update_request,
    execute_next_feature_update_request,
)
from kortravelmap.infra.feature_update_repo import (
    FEATURE_UPDATE_JOB_KIND,
    FEATURE_UPDATE_LOCK_RETRY_AFTER_SECONDS,
    FeatureUpdateLockBusy,
    FeatureUpdateRequest,
    FeatureUpdateRequestPage,
    FeatureUpdateRequestPreview,
    advance_update_request_generation_after_pre_start_failure,
    enqueue_feature_update_request,
    feature_update_scope_advisory_key,
    finish_update_request,
    get_update_request,
    list_update_requests,
    peek_next_update_request,
    preview_feature_update_request,
    start_update_request,
)
from kortravelmap.infra.file_store import S3ObjectStore, StoredObject
from kortravelmap.infra.integrity_violation_repo import (
    DataIntegrityViolation,
    IntegrityObservationReceipt,
    IntegrityObservationRun,
    close_stale_integrity_findings,
    create_data_integrity_violation,
    ensure_integrity_observation_run,
    finalize_integrity_observation_run,
    get_data_integrity_violation,
    list_data_integrity_violations,
    purge_resolved_integrity_findings,
    set_data_integrity_violation_status,
    sync_integrity_findings,
)
from kortravelmap.infra.jobs_repo import (
    ImportJob,
    ImportJobDataset,
    ImportJobDatasetTarget,
    ImportJobEvent,
    bind_import_job_dagster_run,
    cancel_import_job,
    claim_next_import_job,
    enqueue_import_job,
    enqueue_provider_dataset_import_job,
    enqueue_unpaired_import_job,
    finish_import_job,
    get_import_job,
    heartbeat_import_job,
    record_import_job_event,
    recover_stale_running_jobs,
    start_import_job,
    start_provider_dataset_import_job,
    start_unpaired_import_job,
    update_import_job_payload,
)
from kortravelmap.infra.models import (
    Base,
    CuratedFeatureDetailSnapshotRow,
    CuratedFeatureRow,
    CuratedSourceRow,
    CuratedSourceRuleRow,
    CuratedThemeRow,
    DataIntegrityViolationRow,
    DedupReviewQueueRow,
    FeatureConsistencyReportRow,
    FeatureOverrideRow,
    FeatureRow,
    FeatureUpdateRequestRow,
    ImportJobEventRow,
    ImportJobRow,
    IntegrityFindingObservationRow,
    IntegrityObservationRunRow,
    IntegrityObservationScopeRow,
    OfflineUploadRow,
    PipelineCancellationMemberRow,
    PipelineCancellationRow,
    PipelineCancellationRunRow,
    PoiCacheTargetFeatureLinkRow,
    PoiCacheTargetRow,
    ProviderRefreshPolicyRow,
    ProviderSyncStateRow,
    SourceLinkRow,
    SourceRecordRow,
    metadata,
)
from kortravelmap.infra.offline_upload_repo import (
    OfflineUpload,
    OfflineUploadPage,
    attach_offline_upload_load_job,
    create_offline_upload,
    finish_offline_upload_load,
    finish_offline_upload_validation,
    get_offline_upload,
    get_offline_upload_by_checksum,
    list_offline_uploads,
    mark_offline_upload_loading,
    mark_offline_upload_validating,
    reserve_offline_upload_load,
)
from kortravelmap.infra.pipeline_cancellation_repo import (
    PipelineCancellationAttempt,
    PipelineCancellationConflict,
    PipelineCancellationDetail,
    PipelineCancellationInvariantError,
    PipelineCancellationMember,
    PipelineCancellationRun,
    PipelineCancellationScope,
    PipelineCancellationScopeMember,
    PipelineCancellationSummary,
    PipelineCancellationTimelineConflict,
    cancel_queued_pipeline_cancellation_member,
    create_pipeline_cancellation_attempt,
    fill_pipeline_cancellation_canonical_starts,
    finish_pipeline_cancellation_attempt,
    get_current_pipeline_cancellation_detail,
    get_current_pipeline_cancellation_summary,
    get_pipeline_cancellation_detail,
    lock_pipeline_cancellation_root,
    lock_pipeline_hierarchy_for_jobs,
    lock_pipeline_lineage_mutation,
    mark_pipeline_cancellation_run_termination_reserved,
    resolve_pipeline_cancellation_scope,
    retry_pipeline_cancellation_attempt,
    set_pipeline_cancellation_member_result,
    set_pipeline_cancellation_run_result,
    transition_pipeline_cancellation_member,
)
from kortravelmap.infra.poi_cache_target_repo import (
    PoiCacheTarget,
    PoiCacheTargetConflict,
    PoiCacheTargetFeatureLink,
    PoiCacheTargetFeatureLinkCandidate,
    PoiCacheTargetPage,
    deactivate_poi_cache_target_feature_links,
    delete_poi_cache_target,
    get_poi_cache_target,
    get_poi_cache_target_by_key,
    list_active_target_coords,
    list_poi_cache_target_feature_links,
    list_poi_cache_targets,
    mark_poi_cache_targets_refresh_failed,
    mark_poi_cache_targets_refresh_requested,
    mark_poi_cache_targets_refreshed,
    sync_poi_cache_target_feature_links,
    upsert_poi_cache_target,
    upsert_poi_cache_target_feature_link,
)
from kortravelmap.infra.provider_refresh_policy_repo import (
    ProviderRefreshPolicy,
    ProviderRefreshPolicyRevisionConflict,
    ProviderRefreshPolicyRevisionExhausted,
    ProviderRefreshPolicySourceKindImmutable,
    get_provider_refresh_policy,
    list_provider_refresh_policies,
    upsert_provider_refresh_policy,
)
from kortravelmap.infra.scope_repo import (
    CacheTargetFeatureMatch,
    CacheTargetScopeTarget,
    FeatureScopeRow,
    ProviderDatasetScope,
    ScopeResolution,
    SigunguByRadiusResolver,
    count_features_matching_scope,
    resolve_bbox,
    resolve_cache_target_keys,
    resolve_center_radius,
    resolve_feature_ids,
    resolve_provider_dataset,
    resolve_sigungu_by_radius,
)
from kortravelmap.infra.status_repo import StatusCounts, gather_status_counts

__all__ = [
    # advisory_lock (ADR-011 / ADR-039)
    "advisory_lock",
    "advisory_lock_key",
    "try_advisory_lock",
    # cache target generation stream/outbox (ADR-081 T-VN-41A/B/C)
    "CacheTargetAppliedReceipt",
    "CacheTargetClaimAckResult",
    "CacheTargetDeadLetter",
    "CacheTargetDeadLetterPage",
    "CacheTargetDeliveryResult",
    "CacheTargetEventClaim",
    "CacheTargetOutboxEvent",
    "CacheTargetActiveReconciliation",
    "CacheTargetOperation",
    "CacheTargetReconciliationRecord",
    "CacheTargetRefreshMember",
    "CacheTargetRefreshRequestResult",
    "CacheTargetReconciliationResult",
    "CacheTargetRestoreReference",
    "CacheTargetResultEvent",
    "CacheTargetRestoreFenceResult",
    "CacheTargetSourceApplyResult",
    "CacheTargetSourceRecord",
    "CacheTargetSnapshotItem",
    "CacheTargetSnapshotGcBacklog",
    "CacheTargetSnapshotGcBatchResult",
    "CacheTargetSnapshotPage",
    "CacheTargetSnapshotStatus",
    "CacheTargetStreamConflict",
    "CacheTargetStreamControl",
    "CacheTargetStreamStatus",
    "CacheTargetStreamStatusPage",
    "CacheTargetStreamDiscovery",
    "ack_cache_target_events",
    "append_cache_target_links_reconciled_events",
    "append_cache_target_refresh_status_events",
    "advance_cache_target_restore_fence",
    "apply_cache_target_source",
    "begin_cache_target_reconciliation",
    "cache_target_dead_letter_entity_tag",
    "cache_target_event_cursor",
    "cache_target_reconciliation_entity_tag",
    "cache_target_stream_entity_tag",
    "claim_cache_target_events",
    "capture_cache_target_refresh_members",
    "capture_cache_target_refresh_members_by_keys",
    "lock_cache_target_result_streams",
    "complete_cache_target_reconciliation",
    "create_cache_target_refresh_request",
    "fence_restored_cache_target_streams",
    "get_cache_target_dead_letter",
    "get_cache_target_operation",
    "get_cache_target_reconciliation",
    "get_cache_target_reconciliation_snapshot",
    "get_cache_target_refresh_request",
    "get_cache_target_snapshot",
    "get_cache_target_source",
    "get_cache_target_stream",
    "get_cache_target_stream_discovery",
    "lock_cache_target_stream",
    "list_cache_target_restore_references",
    "list_cache_target_dead_letters",
    "list_cache_target_stream_statuses",
    "nack_cache_target_event",
    "parse_cache_target_event_cursor",
    "observe_expired_cache_target_snapshot_backlog",
    "prune_expired_cache_target_snapshots_batch",
    "replay_cache_target_dead_letter",
    "request_cache_target_reconciliation",
    "seal_cache_target_reconciliation",
    # crs (ADR-012 + ADR-030)
    "EPSG_WGS84",
    "EPSG_UTM_K",
    "transformer_4326_to_5179",
    "transformer_5179_to_4326",
    "project_to_5179",
    "project_to_4326",
    # db (ADR-007)
    "make_async_engine",
    "make_async_session_factory",
    "normalize_async_dsn",
    # models (PR#28, ADR-004 / ADR-007 / ADR-018)
    "Base",
    "metadata",
    "CuratedFeatureRow",
    "CuratedSourceRow",
    "CuratedSourceRuleRow",
    "CuratedThemeRow",
    "CuratedFeatureDetailSnapshotRow",
    "FeatureRow",
    "SourceRecordRow",
    "SourceLinkRow",
    "ProviderSyncStateRow",
    "FeatureConsistencyReportRow",
    "DedupReviewQueueRow",
    "ImportJobRow",
    "ImportJobEventRow",
    "FeatureOverrideRow",
    "FeatureUpdateRequestRow",
    "PipelineCancellationRow",
    "PipelineCancellationRunRow",
    "PipelineCancellationMemberRow",
    "IntegrityObservationScopeRow",
    "IntegrityObservationRunRow",
    "IntegrityFindingObservationRow",
    "DataIntegrityViolationRow",
    "PoiCacheTargetRow",
    "PoiCacheTargetFeatureLinkRow",
    "ProviderRefreshPolicyRow",
    "OfflineUploadRow",
    # file_store (ADR-015 S3 호환 객체 저장소)
    "S3ObjectStore",
    "StoredObject",
    # feature_identity (ADR-068 T-VN-32B 경계 alias 해석)
    "FeatureIdentity",
    "FeatureIdentityInvariantError",
    "FeatureIdentityRefError",
    "count_features_missing_identity",
    "get_feature_uuid_map",
    "resolve_feature_identity",
    # feature_repo (ADR-004 raw SQL load 경로)
    "FeatureLoadResult",
    "FeatureSearchPage",
    "FeatureSearchRow",
    "NearbyFeaturePage",
    "NearbyFeatureRow",
    "upsert_feature",
    "upsert_source_record",
    "upsert_source_link",
    "load_bundle",
    "load_bundles",
    "retire_features_absent_from_snapshot",
    "retire_features_by_source_entity_ids",
    "retire_geometryless_area_features_by_source",
    "get_feature_row",
    "get_feature_rows_by_ids",
    "get_public_feature_row",
    "get_public_feature_rows_by_ids",
    "list_active_place_coords",
    "features_in_bbox",
    "search_features",
    "features_nearby_poi_cache_target",
    # admin_feature_repo (ADR-045 T-207c)
    "AdminFeaturePage",
    "AdminFeatureRow",
    "AdminFeatureStateConflict",
    "AdminFeatureStateNotFound",
    "AdminFeatureStatePreconditionFailed",
    "AdminFeatureStateTransition",
    "AdminFeatureStateTransitionAudit",
    "AdminFeatureStateTransitionAuditPage",
    "AdminFeatureStateValidationError",
    "FeatureOverride",
    "DedupReviewPage",
    "DedupReviewRow",
    "list_admin_features",
    "list_admin_feature_state_transitions",
    "transition_admin_feature_state",
    "reactivate_admin_feature_state",
    "list_dedup_reviews",
    "merge_dedup_review",
    "set_dedup_review_decision",
    # dedup_repo (ADR-016 dedup 후보 큐)
    "DedupQueueResult",
    "enqueue_dedup_candidate",
    "enqueue_dedup_candidates",
    "pending_dedup_reviews",
    # dedup_refresh_repo (ADR-045 T-208f)
    "DEDUP_REFRESH_DEFAULT_LIMIT",
    "DedupRefreshFeature",
    "DedupRefreshScope",
    "list_dedup_refresh_features",
    # jobs_repo (ADR-011 작업 큐)
    "ImportJob",
    "ImportJobDataset",
    "ImportJobDatasetTarget",
    "ImportJobEvent",
    "enqueue_unpaired_import_job",
    "enqueue_import_job",
    "enqueue_provider_dataset_import_job",
    "start_unpaired_import_job",
    "start_import_job",
    "start_provider_dataset_import_job",
    "get_import_job",
    "record_import_job_event",
    "update_import_job_payload",
    "bind_import_job_dagster_run",
    "claim_next_import_job",
    "heartbeat_import_job",
    "cancel_import_job",
    "finish_import_job",
    "recover_stale_running_jobs",
    # offline_upload_repo (ADR-045 D-14 / T-208h)
    "OfflineUpload",
    "OfflineUploadPage",
    "attach_offline_upload_load_job",
    "create_offline_upload",
    "get_offline_upload",
    "get_offline_upload_by_checksum",
    "list_offline_uploads",
    "mark_offline_upload_loading",
    "mark_offline_upload_validating",
    "reserve_offline_upload_load",
    "finish_offline_upload_validation",
    "finish_offline_upload_load",
    # feature_update_repo (ADR-045 feature update request queue)
    "FEATURE_UPDATE_JOB_KIND",
    "FEATURE_UPDATE_LOCK_RETRY_AFTER_SECONDS",
    "FeatureUpdateLockBusy",
    "FeatureUpdateRequest",
    "FeatureUpdateRequestPreview",
    "FeatureUpdateRequestPage",
    "advance_update_request_generation_after_pre_start_failure",
    "enqueue_feature_update_request",
    "preview_feature_update_request",
    "peek_next_update_request",
    "feature_update_scope_advisory_key",
    "start_update_request",
    "finish_update_request",
    "get_update_request",
    "list_update_requests",
    # feature_update_active_repo (#686 active identity + dispatch intent)
    "FeatureUpdateDispatchConflict",
    "find_active_provider_dataset_request",
    "is_active_provider_dataset_unique_violation",
    "request_feature_update_dispatch",
    # pipeline_cancellation_repo (ADR-064 T-ADM-C3d)
    "PipelineCancellationAttempt",
    "PipelineCancellationConflict",
    "PipelineCancellationDetail",
    "PipelineCancellationInvariantError",
    "PipelineCancellationTimelineConflict",
    "PipelineCancellationMember",
    "PipelineCancellationRun",
    "PipelineCancellationScope",
    "PipelineCancellationScopeMember",
    "PipelineCancellationSummary",
    "cancel_queued_pipeline_cancellation_member",
    "create_pipeline_cancellation_attempt",
    "retry_pipeline_cancellation_attempt",
    "finish_pipeline_cancellation_attempt",
    "fill_pipeline_cancellation_canonical_starts",
    "get_pipeline_cancellation_detail",
    "get_current_pipeline_cancellation_detail",
    "get_current_pipeline_cancellation_summary",
    "resolve_pipeline_cancellation_scope",
    "lock_pipeline_lineage_mutation",
    "lock_pipeline_cancellation_root",
    "lock_pipeline_hierarchy_for_jobs",
    "mark_pipeline_cancellation_run_termination_reserved",
    "set_pipeline_cancellation_member_result",
    "set_pipeline_cancellation_run_result",
    "transition_pipeline_cancellation_member",
    # feature_update_executor (ADR-045 T-206d)
    "FeatureUpdateExecutionPlan",
    "FeatureUpdateExecutionResult",
    "ProviderDatasetRefreshResult",
    "ProviderDatasetRefreshRunner",
    "ProviderDatasetRefreshScope",
    "SkippedProviderDatasetRefresh",
    "build_feature_update_execution_plan",
    "execute_feature_update_request",
    "execute_next_feature_update_request",
    # feature_operation_repo (ADR-064 T-ADM-C3e-A1)
    "append_dagster_feature_attempt_event",
    "ensure_dagster_feature_operation",
    "finish_dagster_feature_membership",
    "list_reconcilable_dagster_feature_runs",
    "reconcile_dagster_feature_run",
    "record_feature_operation_invariant_conflict",
    # Phase 2 ops repos (ADR-045 T-205c)
    "DataIntegrityViolation",
    "IntegrityObservationReceipt",
    "IntegrityObservationRun",
    "close_stale_integrity_findings",
    "create_data_integrity_violation",
    "ensure_integrity_observation_run",
    "finalize_integrity_observation_run",
    "get_data_integrity_violation",
    "list_data_integrity_violations",
    "list_feature_operation_memberships",
    "purge_resolved_integrity_findings",
    "set_data_integrity_violation_status",
    "sync_integrity_findings",
    "PoiCacheTarget",
    "PoiCacheTargetConflict",
    "PoiCacheTargetFeatureLink",
    "PoiCacheTargetFeatureLinkCandidate",
    "PoiCacheTargetPage",
    "upsert_poi_cache_target",
    "get_poi_cache_target",
    "get_poi_cache_target_by_key",
    "list_poi_cache_targets",
    "list_active_target_coords",
    "delete_poi_cache_target",
    "deactivate_poi_cache_target_feature_links",
    "upsert_poi_cache_target_feature_link",
    "sync_poi_cache_target_feature_links",
    "list_poi_cache_target_feature_links",
    "mark_poi_cache_targets_refresh_requested",
    "mark_poi_cache_targets_refreshed",
    "mark_poi_cache_targets_refresh_failed",
    "ProviderRefreshPolicy",
    "ProviderRefreshPolicyRevisionConflict",
    "ProviderRefreshPolicyRevisionExhausted",
    "ProviderRefreshPolicySourceKindImmutable",
    "upsert_provider_refresh_policy",
    "get_provider_refresh_policy",
    "list_provider_refresh_policies",
    # scope_repo (ADR-045 feature update request preview/scope resolver)
    "FeatureScopeRow",
    "CacheTargetScopeTarget",
    "CacheTargetFeatureMatch",
    "ProviderDatasetScope",
    "ScopeResolution",
    "SigunguByRadiusResolver",
    "resolve_feature_ids",
    "resolve_center_radius",
    "resolve_bbox",
    "resolve_sigungu_by_radius",
    "resolve_provider_dataset",
    "resolve_cache_target_keys",
    "count_features_matching_scope",
    # status_repo (read-only 운영 현황)
    "StatusCounts",
    "gather_status_counts",
]
