"""300 root의 fresh upgrade와 retired lineage 거부 경계를 검증한다.

과거 0200~0236 migration은 active integration에서 replay하지 않는다. handoff source는
final 300 schema를 만든 뒤 test fixture가 raw version row만 0236으로 바꾼 상태다.
실제 historical source의 positive handoff는 root one-shot candidate 실행에서만 검증한다.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import CheckConstraint
from sqlalchemy.dialects import postgresql

from alembic import command
from kortravelmap.infra.application_schema_head import (
    BASELINE_ROOT_REVISION,
    application_schema_head,
)
from tests.integration._application_300_bootstrap import (
    alembic_schema_owner_role,
    bootstrapped_application_300_migrator_dsn,
    upgrade_head_with_application_300_bootstrap,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

pytestmark = pytest.mark.integration

#: 배포가 파생하는 현재 application head. 리터럴 사본을 두지 않는다.
_HEAD = application_schema_head()
_HANDOFF_SOURCE = "0236_tvn41s_compaction_drained"
_HANDOFF_TAG = "application-schema-0236-to-300"


def _with_database(url: str, database: str) -> str:
    parts = urlsplit(url)
    return urlunsplit(parts._replace(path=f"/{database}"))


async def _connect(url: str) -> Any:
    import asyncpg

    parts = urlsplit(url)
    return await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )


async def _admin_execute(url: str, statement: str) -> None:
    connection = await _connect(url)
    try:
        await connection.execute(statement)
    finally:
        await connection.close()


async def _raw_version(url: str) -> tuple[str, ...]:
    connection = await _connect(url)
    try:
        if await connection.fetchval("SELECT to_regclass('public.alembic_version')") is None:
            return ()
        rows = await connection.fetch(
            "SELECT version_num FROM public.alembic_version ORDER BY version_num"
        )
        return tuple(str(row["version_num"]) for row in rows)
    finally:
        await connection.close()


async def _assert_mapped_check_definitions_match(url: str) -> None:
    """ORM CHECK 식을 PostgreSQL에 파싱시켜 live catalog와 의미 단위로 대조한다.

    Alembic의 named CHECK comparator는 이름의 추가·삭제는 잡지만, 같은 이름의 식
    변경을 모두 찾지 못한다. metadata 식을 빈 임시 table에 붙인 뒤 PostgreSQL이
    다시 deparse한 정의끼리 비교하면 `AND` 묶음 같은 표기 차이를 통과시키면서도
    실제 CHECK 의미 drift는 CI에서 막는다.
    """

    import re

    import asyncpg

    from kortravelmap.infra.models import Base

    parts = urlsplit(url)
    connection = await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )
    dialect = postgresql.dialect()
    quote = dialect.identifier_preparer.quote
    mismatches: list[str] = []

    def canonical(definition: str | None) -> str | None:
        """PostgreSQL이 같은 것으로 보는 varchar cast와 IN 집합 순서만 정규화한다."""

        if definition is None:
            return None
        normalized = definition.replace("::character varying::text", "::text").replace(
            "::character varying", "::text"
        )

        def sort_text_array(match: re.Match[str]) -> str:
            items = re.findall(r"'(?:''|[^'])*'::text", match.group(1))
            return f"ARRAY[{', '.join(sorted(items))}]"

        return re.sub(
            r"ARRAY\[((?:'(?:''|[^'])*'::text(?:, )?)+)\](?:::text\[\])?",
            sort_text_array,
            normalized,
        )

    try:
        await connection.execute(
            "SET search_path = public, feature, provider_sync, ops, x_extension"
        )
        for index, table in enumerate(sorted(Base.metadata.tables.values(), key=str)):
            assert table.schema is not None
            checks = sorted(
                (
                    constraint
                    for constraint in table.constraints
                    if isinstance(constraint, CheckConstraint)
                ),
                key=lambda constraint: str(constraint.name),
            )
            if not checks:
                continue

            temporary_table = f"application_300_check_metadata_{index}"
            await connection.execute(
                f"CREATE TEMP TABLE {quote(temporary_table)} "
                f"(LIKE {quote(table.schema)}.{quote(table.name)})"
            )
            for constraint in checks:
                assert constraint.name is not None
                expression = str(
                    constraint.sqltext.compile(
                        dialect=dialect,
                        compile_kwargs={"literal_binds": True},
                    )
                )
                await connection.execute(
                    f"ALTER TABLE pg_temp.{quote(temporary_table)} "
                    f"ADD CONSTRAINT {quote(str(constraint.name))} "
                    f"CHECK ({expression})"
                )

            live_rows = await connection.fetch(
                """
                SELECT con.conname, pg_get_constraintdef(con.oid, true) AS definition
                FROM pg_catalog.pg_constraint AS con
                WHERE con.conrelid = to_regclass($1) AND con.contype = 'c'
                """,
                f"{table.schema}.{table.name}",
            )
            metadata_rows = await connection.fetch(
                """
                SELECT con.conname, pg_get_constraintdef(con.oid, true) AS definition
                FROM pg_catalog.pg_constraint AS con
                WHERE con.conrelid = to_regclass($1) AND con.contype = 'c'
                """,
                f"pg_temp.{temporary_table}",
            )
            live = {row["conname"]: row["definition"] for row in live_rows}
            metadata = {row["conname"]: row["definition"] for row in metadata_rows}
            for name in sorted(live.keys() | metadata.keys()):
                if canonical(live.get(name)) != canonical(metadata.get(name)):
                    mismatches.append(
                        f"{table.schema}.{table.name}.{name}: "
                        f"DB={live.get(name)!r}, ORM={metadata.get(name)!r}"
                    )
    finally:
        await connection.close()

    assert not mismatches, "CHECK expression catalog drift:\n" + "\n".join(mismatches)


@pytest.fixture
async def application_300_config(
    pg_container: object,
) -> AsyncIterator[tuple[Config, str]]:
    """fresh DB를 300으로 올린 Config와 admin DSN을 제공한다."""

    from kortravelmap.infra.db import normalize_async_dsn

    raw_dsn = pg_container.get_connection_url()  # type: ignore[attr-defined]
    database = f"application_300_metadata_{uuid4().hex}"
    await _admin_execute(raw_dsn, f'CREATE DATABASE "{database}"')
    admin_dsn = normalize_async_dsn(_with_database(raw_dsn, database))
    root = Path(__file__).resolve().parents[2]  # noqa: ASYNC240
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    config.set_main_option("sqlalchemy.url", admin_dsn)
    try:
        await upgrade_head_with_application_300_bootstrap(config, admin_dsn)
        yield config, admin_dsn
    finally:
        await _admin_execute(raw_dsn, f'DROP DATABASE "{database}" WITH (FORCE)')


async def _prepare_logical_0236(
    config: Config, admin_dsn: str, *, expected_before: str = _HEAD
) -> None:
    """retired source를 실행하지 않고 exact source version facet을 fixture로 만든다.

    ``expected_before``는 호출자가 **선언**한다. handoff fixture는 baseline root에서
    멈추고 metadata fixture는 head까지 올리므로, 여기서 하나로 가정하면 둘 중 하나가
    반드시 틀린다.
    """
    del config
    assert await _raw_version(admin_dsn) == (expected_before,)
    await _admin_execute(
        admin_dsn,
        "SET ROLE ktm_feature_schema_owner; "
        "DROP TABLE public.alembic_version; "
        "CREATE TABLE public.alembic_version ("
        "version_num varchar(32) NOT NULL, "
        "CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)"
        "); "
        f"INSERT INTO public.alembic_version VALUES ('{_HANDOFF_SOURCE}'); "
        "RESET ROLE",
    )
    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
async def test_fresh_upgrade_rolls_back_when_public_text_search_residue_appears_after_bootstrap(
    pg_container: object,
) -> None:
    """bootstrap 뒤 끼어든 public semantic object는 `300` metadata를 남기지 않는다.

    official fresh image → role/extension bootstrap → migration 사이에는 normal runtime이
    개입하지 않아야 한다. 그래도 외부 superuser mutation을 repair하지 않고 final
    migration transaction 전체를 rollback해야 하므로, raw Alembic head와 application
    relation 모두 비어 있어야 한다.
    """

    from kortravelmap.infra.db import normalize_async_dsn

    raw_dsn = pg_container.get_connection_url()  # type: ignore[attr-defined]
    database = f"application_300_public_residue_{uuid4().hex}"
    await _admin_execute(raw_dsn, f'CREATE DATABASE "{database}"')
    admin_dsn = normalize_async_dsn(_with_database(raw_dsn, database))
    root = Path(__file__).resolve().parents[2]  # noqa: ASYNC240
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    try:
        config.set_main_option(
            "sqlalchemy.url",
            await bootstrapped_application_300_migrator_dsn(admin_dsn),
        )
        await _admin_execute(
            admin_dsn,
            "CREATE TEXT SEARCH CONFIGURATION "
            "public.application_300_late_residue "
            "(PARSER = pg_catalog.default)",
        )

        with alembic_schema_owner_role(), pytest.raises(
            Exception, match="public residue catalog is not empty"
        ):
            await asyncio.to_thread(command.upgrade, config, "head")

        assert await _raw_version(admin_dsn) == ()
        connection = await _connect(admin_dsn)
        try:
            application_relation_count = await connection.fetchval(
                """
                SELECT count(*)
                FROM pg_catalog.pg_class AS object
                JOIN pg_catalog.pg_namespace AS namespace
                  ON namespace.oid = object.relnamespace
                WHERE namespace.nspname IN ('feature', 'provider_sync', 'ops')
                  AND object.relkind IN ('r', 'p', 'v', 'm', 'f', 'S')
                """
            )
        finally:
            await connection.close()
        assert application_relation_count == 0
    finally:
        await _admin_execute(raw_dsn, f'DROP DATABASE "{database}" WITH (FORCE)')


async def _stamp(
    config: Config,
    *,
    # handoff의 목적지는 **baseline root**다. head가 아니다. 기본값을 `_HEAD`로 두면
    # migration이 하나 붙는 순간 `is_sanctioned`가 거짓이 되어, 이 helper를 쓰는 음성
    # 테스트들이 자기가 노리던 오류 대신 "generic Alembic stamp is unsupported"를 받는다.
    revision: str = BASELINE_ROOT_REVISION,
    purge: bool = True,
    tag: str | None = _HANDOFF_TAG,
) -> None:
    with alembic_schema_owner_role():
        await asyncio.to_thread(
            # intentional-squash-boundary-rejection: negative handoff gate inputs.
            command.stamp,
            config,
            revision,
            purge=purge,
            tag=tag,
        )


@pytest.mark.filterwarnings("ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning")
@pytest.mark.filterwarnings("ignore:Computed default on:UserWarning")
@pytest.mark.asyncio
async def test_fresh_300_upgrade_is_metadata_clean(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config

    assert await _raw_version(admin_dsn) == (_HEAD,)
    with alembic_schema_owner_role():
        try:
            await asyncio.to_thread(command.check, config)
        except AutogenerateDiffsDetected as exc:  # pragma: no cover
            pytest.fail(f"fresh 300 baseline metadata drift: {exc}")
    await _assert_mapped_check_definitions_match(admin_dsn)


@pytest.mark.asyncio
async def test_public_config_attribute_cannot_authorize_0236_to_300_stamp(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)
    # 공격자가 arbitrary Config attribute를 넣어도 root-only capability를 만들 수는 없다.
    config.attributes["application_schema_0236_to_300_handoff_authorized"] = True
    try:
        with pytest.raises(RuntimeError, match="root-owned one-shot capability"):
            await _stamp(config)
    finally:
        config.attributes.pop("application_schema_0236_to_300_handoff_authorized", None)

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
async def test_generic_upgrade_from_0236_is_rejected_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)

    with alembic_schema_owner_role(), pytest.raises(
        RuntimeError,
        match="controlled application-schema 0236-to-300 handoff",
    ):
        await asyncio.to_thread(command.upgrade, config, "head")

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("revision", "purge", "tag"),
    [
        (_HEAD, True, None),
        (_HEAD, False, _HANDOFF_TAG),
        ("head", True, _HANDOFF_TAG),
        ("base", True, _HANDOFF_TAG),
    ],
)
async def test_unsanctioned_stamp_keeps_0236_raw_version(
    application_300_config: tuple[Config, str],
    revision: str,
    purge: bool,
    tag: str | None,
) -> None:
    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)

    with pytest.raises(RuntimeError, match="generic Alembic stamp is unsupported"):
        await _stamp(
            config,
            revision=revision,
            purge=purge,
            tag=tag,
        )

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
async def test_handoff_rejects_non_0236_raw_version_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    await _admin_execute(
        admin_dsn,
        "UPDATE public.alembic_version SET version_num = '0235_m05_reconciliation_delivery'",
    )

    with pytest.raises(RuntimeError, match="requires exactly one raw source head"):
        await _stamp(config)

    assert await _raw_version(admin_dsn) == ("0235_m05_reconciliation_delivery",)


@pytest.mark.asyncio
async def test_downgrade_is_rejected_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config

    with alembic_schema_owner_role(), pytest.raises(
        RuntimeError,
        match="300_schema_baseline is forward-only",
    ):
        await asyncio.to_thread(
            # intentional-squash-boundary-rejection: all downgrade targets are forbidden.
            command.downgrade,
            config,
            "base",
        )

    assert await _raw_version(admin_dsn) == (_HEAD,)
