"""300 root의 fresh upgrade와 exact 0236 → 300 handoff를 검증한다.

과거 0200~0236 migration은 active integration에서 replay하지 않는다. handoff source는
final 300 schema를 만든 뒤 test fixture가 raw version row만 0236으로 바꾼 상태다.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import CheckConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import DBAPIError

from alembic import command
from tests.integration._application_300_bootstrap import (
    alembic_schema_owner_role,
    upgrade_head_with_application_300_bootstrap,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

pytestmark = pytest.mark.integration

_HEAD = "300"
_HANDOFF_SOURCE = "0236_tvn41s_compaction_drained"
_HANDOFF_TAG = "application-schema-0236-to-300"
_HANDOFF_CONFIG_ATTRIBUTE = "application_schema_0236_to_300_handoff_authorized"


def _with_database(url: str, database: str) -> str:
    parts = urlsplit(url)
    return urlunsplit(parts._replace(path=f"/{database}"))


async def _connect(url: str) -> Any:
    import asyncpg

    parts = urlsplit(url)
    return await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )


async def _admin_execute(url: str, statement: str) -> None:
    connection = await _connect(url)
    try:
        await connection.execute(statement)
    finally:
        await connection.close()


async def _raw_version(url: str) -> tuple[str, ...]:
    connection = await _connect(url)
    try:
        if await connection.fetchval("SELECT to_regclass('public.alembic_version')") is None:
            return ()
        rows = await connection.fetch(
            "SELECT version_num FROM public.alembic_version ORDER BY version_num"
        )
        return tuple(str(row["version_num"]) for row in rows)
    finally:
        await connection.close()


async def _catalog_fingerprint(url: str) -> tuple[str, ...]:
    """handoff가 version row 외 application catalog를 건드리지 않는지 확인한다."""

    connection = await _connect(url)
    try:
        rows = await connection.fetch(
            """
            SELECT item
            FROM (
                SELECT 'relation:' || namespace.nspname || '.' || relation.relname
                       || ':' || relation.relkind::text || ':'
                       || pg_get_userbyid(relation.relowner) AS item
                FROM pg_catalog.pg_class AS relation
                JOIN pg_catalog.pg_namespace AS namespace
                  ON namespace.oid = relation.relnamespace
                WHERE namespace.nspname IN ('feature', 'provider_sync', 'ops')
                  AND relation.relkind IN ('r', 'p', 'v', 'm', 'S', 'f')
                UNION ALL
                SELECT 'routine:' || namespace.nspname || '.' || routine.proname
                       || '(' || pg_get_function_identity_arguments(routine.oid) || '):'
                       || pg_get_userbyid(routine.proowner)
                FROM pg_catalog.pg_proc AS routine
                JOIN pg_catalog.pg_namespace AS namespace
                  ON namespace.oid = routine.pronamespace
                WHERE namespace.nspname IN ('feature', 'provider_sync', 'ops')
                UNION ALL
                SELECT 'constraint:' || namespace.nspname || '.' || relation.relname
                       || '.' || con.conname || ':'
                       || pg_get_constraintdef(con.oid, true)
                FROM pg_catalog.pg_constraint AS con
                JOIN pg_catalog.pg_class AS relation ON relation.oid = con.conrelid
                JOIN pg_catalog.pg_namespace AS namespace
                  ON namespace.oid = relation.relnamespace
                WHERE namespace.nspname IN ('feature', 'provider_sync', 'ops')
            ) AS catalog
            ORDER BY item
            """
        )
        return tuple(str(row["item"]) for row in rows)
    finally:
        await connection.close()


async def _assert_mapped_check_definitions_match(url: str) -> None:
    """ORM CHECK 식을 PostgreSQL에 파싱시켜 live catalog와 의미 단위로 대조한다.

    Alembic의 named CHECK comparator는 이름의 추가·삭제는 잡지만, 같은 이름의 식
    변경을 모두 찾지 못한다. metadata 식을 빈 임시 table에 붙인 뒤 PostgreSQL이
    다시 deparse한 정의끼리 비교하면 `AND` 묶음 같은 표기 차이를 통과시키면서도
    실제 CHECK 의미 drift는 CI에서 막는다.
    """

    import re

    import asyncpg

    from kortravelmap.infra.models import Base

    parts = urlsplit(url)
    connection = await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )
    dialect = postgresql.dialect()
    quote = dialect.identifier_preparer.quote
    mismatches: list[str] = []

    def canonical(definition: str | None) -> str | None:
        """PostgreSQL이 같은 것으로 보는 varchar cast와 IN 집합 순서만 정규화한다."""

        if definition is None:
            return None
        normalized = definition.replace("::character varying::text", "::text").replace(
            "::character varying", "::text"
        )

        def sort_text_array(match: re.Match[str]) -> str:
            items = re.findall(r"'(?:''|[^'])*'::text", match.group(1))
            return f"ARRAY[{', '.join(sorted(items))}]"

        return re.sub(
            r"ARRAY\[((?:'(?:''|[^'])*'::text(?:, )?)+)\](?:::text\[\])?",
            sort_text_array,
            normalized,
        )

    try:
        await connection.execute(
            "SET search_path = public, feature, provider_sync, ops, x_extension"
        )
        for index, table in enumerate(sorted(Base.metadata.tables.values(), key=str)):
            assert table.schema is not None
            checks = sorted(
                (
                    constraint
                    for constraint in table.constraints
                    if isinstance(constraint, CheckConstraint)
                ),
                key=lambda constraint: str(constraint.name),
            )
            if not checks:
                continue

            temporary_table = f"application_300_check_metadata_{index}"
            await connection.execute(
                f"CREATE TEMP TABLE {quote(temporary_table)} "
                f"(LIKE {quote(table.schema)}.{quote(table.name)})"
            )
            for constraint in checks:
                assert constraint.name is not None
                expression = str(
                    constraint.sqltext.compile(
                        dialect=dialect,
                        compile_kwargs={"literal_binds": True},
                    )
                )
                await connection.execute(
                    f"ALTER TABLE pg_temp.{quote(temporary_table)} "
                    f"ADD CONSTRAINT {quote(str(constraint.name))} "
                    f"CHECK ({expression})"
                )

            live_rows = await connection.fetch(
                """
                SELECT con.conname, pg_get_constraintdef(con.oid, true) AS definition
                FROM pg_catalog.pg_constraint AS con
                WHERE con.conrelid = to_regclass($1) AND con.contype = 'c'
                """,
                f"{table.schema}.{table.name}",
            )
            metadata_rows = await connection.fetch(
                """
                SELECT con.conname, pg_get_constraintdef(con.oid, true) AS definition
                FROM pg_catalog.pg_constraint AS con
                WHERE con.conrelid = to_regclass($1) AND con.contype = 'c'
                """,
                f"pg_temp.{temporary_table}",
            )
            live = {row["conname"]: row["definition"] for row in live_rows}
            metadata = {row["conname"]: row["definition"] for row in metadata_rows}
            for name in sorted(live.keys() | metadata.keys()):
                if canonical(live.get(name)) != canonical(metadata.get(name)):
                    mismatches.append(
                        f"{table.schema}.{table.name}.{name}: "
                        f"DB={live.get(name)!r}, ORM={metadata.get(name)!r}"
                    )
    finally:
        await connection.close()

    assert not mismatches, "CHECK expression catalog drift:\n" + "\n".join(mismatches)


@pytest.fixture
async def application_300_config(
    pg_container: object,
) -> AsyncIterator[tuple[Config, str]]:
    """fresh DB를 300으로 올린 Config와 admin DSN을 제공한다."""

    from kortravelmap.infra.db import normalize_async_dsn

    raw_dsn = pg_container.get_connection_url()  # type: ignore[attr-defined]
    database = f"application_300_metadata_{uuid4().hex}"
    await _admin_execute(raw_dsn, f'CREATE DATABASE "{database}"')
    admin_dsn = normalize_async_dsn(_with_database(raw_dsn, database))
    root = Path(__file__).resolve().parents[2]  # noqa: ASYNC240
    config = Config(str(root / "alembic.ini"))
    config.set_main_option("script_location", str(root / "alembic"))
    config.set_main_option("sqlalchemy.url", admin_dsn)
    try:
        await upgrade_head_with_application_300_bootstrap(config, admin_dsn)
        yield config, admin_dsn
    finally:
        await _admin_execute(raw_dsn, f'DROP DATABASE "{database}" WITH (FORCE)')


async def _prepare_logical_0236(config: Config, admin_dsn: str) -> tuple[str, ...]:
    """retired source를 실행하지 않고 exact raw source row만 fixture로 만든다."""

    del config
    assert await _raw_version(admin_dsn) == (_HEAD,)
    before = await _catalog_fingerprint(admin_dsn)
    await _admin_execute(
        admin_dsn,
        f"UPDATE public.alembic_version SET version_num = '{_HANDOFF_SOURCE}'",
    )
    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)
    return before


async def _stamp(
    config: Config,
    *,
    revision: str = _HEAD,
    purge: bool = True,
    tag: str | None = _HANDOFF_TAG,
    authorized: bool = True,
) -> None:
    if authorized:
        config.attributes[_HANDOFF_CONFIG_ATTRIBUTE] = True
    else:
        config.attributes.pop(_HANDOFF_CONFIG_ATTRIBUTE, None)
    with alembic_schema_owner_role():
        await asyncio.to_thread(
            # intentional-squash-boundary-rejection: negative handoff gate inputs.
            command.stamp,
            config,
            revision,
            purge=purge,
            tag=tag,
        )


@pytest.mark.filterwarnings("ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning")
@pytest.mark.filterwarnings("ignore:Computed default on:UserWarning")
@pytest.mark.asyncio
async def test_fresh_300_upgrade_is_metadata_clean(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config

    assert await _raw_version(admin_dsn) == (_HEAD,)
    with alembic_schema_owner_role():
        try:
            await asyncio.to_thread(command.check, config)
        except AutogenerateDiffsDetected as exc:  # pragma: no cover
            pytest.fail(f"fresh 300 baseline metadata drift: {exc}")
    await _assert_mapped_check_definitions_match(admin_dsn)


@pytest.mark.asyncio
async def test_0236_to_300_handoff_stamps_only_metadata(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    before = await _prepare_logical_0236(config, admin_dsn)

    await _stamp(config)

    assert await _raw_version(admin_dsn) == (_HEAD,)
    assert await _catalog_fingerprint(admin_dsn) == before
    with alembic_schema_owner_role():
        await asyncio.to_thread(command.current, config)


@pytest.mark.asyncio
async def test_generic_upgrade_from_0236_is_rejected_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)

    with alembic_schema_owner_role(), pytest.raises(
        RuntimeError,
        match="controlled application-schema 0236-to-300 handoff",
    ):
        await asyncio.to_thread(command.upgrade, config, "head")

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("revision", "purge", "tag", "authorized"),
    [
        (_HEAD, True, None, True),
        (_HEAD, False, _HANDOFF_TAG, True),
        ("head", True, _HANDOFF_TAG, True),
        ("base", True, _HANDOFF_TAG, True),
        (_HEAD, True, _HANDOFF_TAG, False),
    ],
)
async def test_unsanctioned_stamp_keeps_0236_raw_version(
    application_300_config: tuple[Config, str],
    revision: str,
    purge: bool,
    tag: str | None,
    authorized: bool,
) -> None:
    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)

    with pytest.raises(RuntimeError, match="generic Alembic stamp is unsupported"):
        await _stamp(
            config,
            revision=revision,
            purge=purge,
            tag=tag,
            authorized=authorized,
        )

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)


@pytest.mark.asyncio
async def test_handoff_rejects_non_0236_raw_version_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config
    await _admin_execute(
        admin_dsn,
        "UPDATE public.alembic_version SET version_num = '0235_m05_reconciliation_delivery'",
    )

    with pytest.raises(RuntimeError, match="requires exactly one raw source head"):
        await _stamp(config)

    assert await _raw_version(admin_dsn) == ("0235_m05_reconciliation_delivery",)


@pytest.mark.asyncio
async def test_downgrade_is_rejected_without_mutation(
    application_300_config: tuple[Config, str],
) -> None:
    config, admin_dsn = application_300_config

    with alembic_schema_owner_role(), pytest.raises(
        RuntimeError,
        match="300_schema_baseline is forward-only",
    ):
        await asyncio.to_thread(
            # intentional-squash-boundary-rejection: all downgrade targets are forbidden.
            command.downgrade,
            config,
            "base",
        )

    assert await _raw_version(admin_dsn) == (_HEAD,)


@pytest.mark.asyncio
async def test_handoff_transaction_rolls_back_when_commit_time_postflight_fails(
    application_300_config: tuple[Config, str],
) -> None:
    """deferred trigger가 commit에서 실패해도 purge된 source row가 되살아야 한다."""

    config, admin_dsn = application_300_config
    await _prepare_logical_0236(config, admin_dsn)
    await _admin_execute(
        admin_dsn,
        """
        CREATE FUNCTION public.application_300_force_handoff_rollback()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'application-300 handoff commit probe';
        END
        $$;
        CREATE CONSTRAINT TRIGGER application_300_handoff_commit_probe
        AFTER INSERT ON public.alembic_version
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION public.application_300_force_handoff_rollback();
        """,
    )

    with pytest.raises(DBAPIError, match="application-300 handoff commit probe"):
        await _stamp(config)

    assert await _raw_version(admin_dsn) == (_HANDOFF_SOURCE,)
