"""§8.1 gate — 빈 PostGIS DB → ``alembic upgrade head`` → ``alembic check`` clean.

ADR-075 D-12-2 / T-VN-19. 모든 app-owned table이 ``models.metadata``에 매핑되거나
``alembic/env.py``의 ``include_object``로 명시 제외돼, freshly-migrated 빈 DB에서
autogenerate diff가 0건임을 상시 검증한다. 새 migration이 metadata와 어긋나거나
(예: 컬럼/인덱스/제약 추가) 새 table이 매핑/제외 목록에서 빠지면 이 테스트가
실패해 CI가 막는다(F-10 회귀 gate).

pollution 없는 "빈 PostGIS DB" 전제를 보장하려고 컨테이너 안에 전용 DB를 새로
만들어 그 위에서만 upgrade/check를 실행한다(다른 session fixture와 격리).
head 적용 뒤 infra owner가 별도로 설치할 수 있는 ``postgis_topology``도 추가해
production shared-DB의 extension-owned ``topology`` schema를 재현한다.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import TYPE_CHECKING
from urllib.parse import urlsplit, urlunsplit

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.exc import DBAPIError

from alembic import command

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

pytestmark = pytest.mark.integration

_GATE_DB = "alembic_metadata_gate"


def _with_database(url: str, database: str) -> str:
    parts = urlsplit(url)
    return urlunsplit(parts._replace(path=f"/{database}"))


async def _admin_execute(default_url: str, statement: str) -> None:
    """컨테이너 기본 DB에 asyncpg autocommit으로 DDL(CREATE/DROP DATABASE) 실행."""

    import asyncpg  # local import — dev/integration 전용 의존.

    parts = urlsplit(default_url)
    conn = await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )
    try:
        await conn.execute(statement)
    finally:
        await conn.close()


async def _admin_fetchval(default_url: str, statement: str) -> object:
    """컨테이너 DB의 단일 값을 admin 자격으로 읽는다."""

    import asyncpg

    parts = urlsplit(default_url)
    conn = await asyncpg.connect(
        user=parts.username,
        password=parts.password,
        host=parts.hostname,
        port=parts.port,
        database=(parts.path or "/postgres").lstrip("/"),
    )
    try:
        return await conn.fetchval(statement)
    finally:
        await conn.close()


async def _upgrade_to_head_as_migrator(cfg: Config) -> str:
    """배포와 같은 경로로 head까지 올리고 **admin(superuser) DSN**을 돌려준다.

    배포 경로는 migrator LOGIN → ``SET ROLE`` schema owner다(ADR-090). 그래서 이
    함수는 ``cfg``의 URL을 migrator 자격으로 바꿔치운다. 반환값은 바꿔치우기 **전**의
    fixture DSN, 즉 컨테이너 superuser 자격이다 — 이후 admin DDL은 반드시 이 반환값을
    써야 한다.

    ``cfg``에서 다시 읽어 쓰면 안 되는 이유: ``ktm_feature_migrator``는 정의상
    NOCREATEDB·NOINHERIT이고 gate DB의 owner도 아니다(0095가 검증하는 restricted
    migrator의 성질 그 자체다). 그 자격으로 ``CREATE EXTENSION``이나 topology schema
    쓰기를 걸면 ``permission denied for database``가 난다. 애초에 아래 두 admin
    단계는 app migrator의 일이 아니라 production에서 infra owner가 별도로 하는
    일이므로, 자격을 섞지 않는 것이 재현하려는 상황과도 맞는다.
    """

    from tests.integration._tvn34_migration_bootstrap import (
        alembic_schema_owner_role,
        bootstrapped_migrator_dsn,
    )

    admin_dsn = cfg.get_main_option("sqlalchemy.url")
    assert admin_dsn is not None
    cfg.set_main_option("sqlalchemy.url", await bootstrapped_migrator_dsn(admin_dsn))
    with alembic_schema_owner_role():
        await asyncio.to_thread(command.upgrade, cfg, "head")
    return admin_dsn


async def _check_as_schema_owner(cfg: Config) -> None:
    """``alembic check``를 upgrade와 **같은 자격**으로 돌린다.

    check는 읽기만 하지만, 그 읽기 대상이 ``alembic_version``과 app schema다. 둘 다
    owner가 ``ktm_feature_schema_owner``이고 ``ktm_feature_migrator``는 NOINHERIT라
    ``SET ROLE`` 없이는 group 권한이 서지 않는다 — 그대로 두면 첫 질의부터
    ``permission denied for table alembic_version``이 난다. 배포에서도 migrator
    툴체인은 upgrade든 check든 항상 SET ROLE 경유로 돈다(ADR-090)."""

    from tests.integration._tvn34_migration_bootstrap import alembic_schema_owner_role

    with alembic_schema_owner_role():
        await asyncio.to_thread(command.check, cfg)


async def _install_postgis_topology_fixture(database_url: str) -> None:
    """production처럼 head 적용 뒤 topology extension 객체를 추가한다."""

    await _admin_execute(
        database_url,
        "CREATE EXTENSION IF NOT EXISTS postgis_topology",
    )
    await _admin_execute(
        database_url,
        """
        DO $$
        BEGIN
            IF to_regclass('topology.layer') IS NULL
               OR to_regclass('topology.topology') IS NULL THEN
                RAISE EXCEPTION 'postgis_topology fixture is incomplete';
            END IF;
        END
        $$
        """,
    )


@pytest.fixture
async def gate_alembic_config(pg_container: object) -> AsyncIterator[Config]:
    """전용 빈 DB를 만들고 alembic Config를 반환, 종료 시 DB를 제거한다."""

    from kortravelmap.infra.db import normalize_async_dsn

    raw_dsn = pg_container.get_connection_url()  # type: ignore[attr-defined]
    await _admin_execute(raw_dsn, f'DROP DATABASE IF EXISTS "{_GATE_DB}"')
    await _admin_execute(raw_dsn, f'CREATE DATABASE "{_GATE_DB}"')

    gate_async_dsn = normalize_async_dsn(_with_database(raw_dsn, _GATE_DB))
    root = Path(__file__).resolve().parents[2]  # noqa: ASYNC240 — 순수 경로 연산.
    cfg = Config(str(root / "alembic.ini"))
    cfg.set_main_option("script_location", str(root / "alembic"))
    cfg.set_main_option("sqlalchemy.url", gate_async_dsn)
    try:
        yield cfg
    finally:
        await _admin_execute(raw_dsn, f'DROP DATABASE IF EXISTS "{_GATE_DB}" WITH (FORCE)')


# alembic check(CLI)은 통과하지만 pytest ``filterwarnings=error``가 아래 두 양성
# 경고를 치명 오류로 승격시키므로 이 테스트에서만 허용한다(정합 판정과 무관):
#  1) source_entities ↔ source_records 의 deferrable 상호 FK(head-pointer 분리,
#     ADR-063)라 SQLAlchemy가 table을 위상 정렬하지 못한다는 advisory SAWarning.
#  2) ``features.coord_5179`` STORED generated 컬럼의 computed default는 수정 불가
#     라는 alembic UserWarning(ADR-012 — autogenerate가 손대지 못할 뿐 drift 아님).
@pytest.mark.filterwarnings(
    "ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning"
)
@pytest.mark.filterwarnings("ignore:Computed default on:UserWarning")
async def test_alembic_check_clean_on_freshly_migrated_db(
    gate_alembic_config: Config,
) -> None:
    """빈 PostGIS DB에 head까지 올린 뒤 ``alembic check``가 diff 0건이어야 한다.

    실패 시 ``AutogenerateDiffsDetected``의 메시지가 어떤 table/컬럼/인덱스가
    metadata와 어긋났는지 그대로 노출한다 — 새 migration은 models.py 매핑 또는
    env.py include_object 목록을 함께 갱신해야 한다.
    """

    cfg = gate_alembic_config
    admin_dsn = await _upgrade_to_head_as_migrator(cfg)
    # topology extension 설치는 infra owner 몫이다 — migrator 자격이 아닌 admin DSN.
    await _install_postgis_topology_fixture(admin_dsn)
    try:
        await _check_as_schema_owner(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover — 회귀 시에만.
        pytest.fail(
            "alembic check detected metadata↔DB drift on a freshly-migrated DB "
            "(ADR-075 D-12-2, T-VN-19). Map the new table/column into "
            "kortravelmap.infra.models or add it to env.py include_object, or fix "
            f"the migration:\n{exc}"
        )


@pytest.mark.filterwarnings(
    "ignore:Cannot correctly sort tables:sqlalchemy.exc.SAWarning"
)
@pytest.mark.filterwarnings("ignore:Computed default on:UserWarning")
async def test_alembic_check_detects_non_extension_topology_table(
    gate_alembic_config: Config,
) -> None:
    """topology schema의 비-extension 객체는 drift에서 숨기지 않는다."""

    cfg = gate_alembic_config
    admin_dsn = await _upgrade_to_head_as_migrator(cfg)
    # topology 객체를 만드는 쪽은 둘 다 infra owner다 — extension 본체도, 그 schema에
    # 섞여 들어온 비-extension sentinel도. migrator DSN으로는 애초에 만들 수 없다.
    await _install_postgis_topology_fixture(admin_dsn)
    await _admin_execute(
        admin_dsn,
        "CREATE TABLE topology.app_drift_sentinel (id bigint PRIMARY KEY)",
    )

    with pytest.raises(AutogenerateDiffsDetected, match="app_drift_sentinel"):
        await _check_as_schema_owner(cfg)


async def test_squash_boundary_rejects_stamp_below_0200_before_mutation(
    gate_alembic_config: Config,
) -> None:
    """0200 아래 stamp는 version table을 비우기 전에 fail-close한다."""

    from tests.integration._tvn34_migration_bootstrap import alembic_schema_owner_role

    cfg = gate_alembic_config
    admin_dsn = await _upgrade_to_head_as_migrator(cfg)
    with alembic_schema_owner_role(), pytest.raises(
        RuntimeError,
        match="0200 is forward-only",
    ):
        await asyncio.to_thread(
            command.stamp,
            cfg,
            "base",
        )  # intentional-squash-boundary-rejection

    assert await _admin_fetchval(
        admin_dsn,
        "SELECT version_num FROM public.alembic_version",
    ) == "0223_tvn40_identity_mappings"


async def test_existing_0104_bridge_upgrades_to_tvn40_head_without_baseline_replay(
    gate_alembic_config: Config,
) -> None:
    """기존 n150 `0104` revision은 baseline 재실행 없이 T-VN-40만 적용한다."""

    from tests.integration._tvn34_migration_bootstrap import (
        alembic_schema_owner_role,
        bootstrapped_migrator_dsn,
    )

    cfg = gate_alembic_config
    admin_dsn = cfg.get_main_option("sqlalchemy.url")
    assert admin_dsn is not None
    cfg.set_main_option("sqlalchemy.url", await bootstrapped_migrator_dsn(admin_dsn))
    with alembic_schema_owner_role():
        await asyncio.to_thread(command.upgrade, cfg, "0200_schema_baseline")
        # Baseline과 catalog-equal인 fixture를 기존 prod revision으로 표시한다. 이 stamp는
        # 테스트 setup 전용이며 production 전환 절차가 아니다.
        await asyncio.to_thread(command.stamp, cfg, "0104_tvn36_final_fence")
        await asyncio.to_thread(command.upgrade, cfg, "head")

    assert await _admin_fetchval(
        admin_dsn,
        "SELECT version_num FROM public.alembic_version",
    ) == "0223_tvn40_identity_mappings"
    assert await _admin_fetchval(
        admin_dsn,
        "SELECT to_regclass('feature.theme_feature_candidates') IS NOT NULL",
    ) is True


async def test_0200_rejects_unsafe_preprovisioned_role_before_schema_ddl(
    gate_alembic_config: Config,
) -> None:
    """bootstrap role 속성이 unsafe면 baseline table을 만들기 전에 거부한다."""

    from tests.integration._tvn34_migration_bootstrap import (
        alembic_schema_owner_role,
        bootstrapped_migrator_dsn,
    )

    cfg = gate_alembic_config
    admin_dsn = cfg.get_main_option("sqlalchemy.url")
    assert admin_dsn is not None
    cfg.set_main_option("sqlalchemy.url", await bootstrapped_migrator_dsn(admin_dsn))
    await _admin_execute(
        admin_dsn,
        "ALTER ROLE ktm_curation_command_owner REPLICATION",
    )
    try:
        with alembic_schema_owner_role(), pytest.raises(
            DBAPIError,
            match="application NOLOGIN role is missing or unsafe",
        ):
            await asyncio.to_thread(command.upgrade, cfg, "0200_schema_baseline")
        assert await _admin_fetchval(
            admin_dsn,
            "SELECT to_regclass('feature.features') IS NULL",
        ) is True
    finally:
        await _admin_execute(
            admin_dsn,
            "ALTER ROLE ktm_curation_command_owner NOREPLICATION",
        )


async def test_0202_rejects_membership_option_and_extra_edge_drift(
    gate_alembic_config: Config,
) -> None:
    """0202는 expected edge option 변화와 교차 executor edge를 모두 거부한다."""

    from tests.integration._tvn34_migration_bootstrap import (
        alembic_schema_owner_role,
        bootstrapped_migrator_dsn,
    )

    cfg = gate_alembic_config
    admin_dsn = cfg.get_main_option("sqlalchemy.url")
    assert admin_dsn is not None
    cfg.set_main_option("sqlalchemy.url", await bootstrapped_migrator_dsn(admin_dsn))
    with alembic_schema_owner_role():
        await asyncio.to_thread(command.upgrade, cfg, "0200_schema_baseline")

    mutations = (
        (
            "GRANT ktm_curation_admin_executor TO ktm_feature_api_runtime "
            "WITH ADMIN TRUE, INHERIT TRUE, SET FALSE",
            "GRANT ktm_curation_admin_executor TO ktm_feature_api_runtime "
            "WITH ADMIN FALSE, INHERIT TRUE, SET FALSE",
        ),
        (
            "GRANT ktm_curation_provider_executor TO ktm_feature_api_runtime "
            "WITH ADMIN FALSE, INHERIT TRUE, SET FALSE",
            "REVOKE ktm_curation_provider_executor FROM ktm_feature_api_runtime",
        ),
    )
    for mutation, restore in mutations:
        await _admin_execute(admin_dsn, mutation)
        try:
            with alembic_schema_owner_role(), pytest.raises(
                DBAPIError,
                match="application role membership graph is not exact",
            ):
                await asyncio.to_thread(command.upgrade, cfg, "0202_tvn40_curation_receipts")
            assert await _admin_fetchval(
                admin_dsn,
                "SELECT version_num FROM public.alembic_version",
            ) == "0200_schema_baseline"
        finally:
            await _admin_execute(admin_dsn, restore)
