#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/load-env.sh
source "$ROOT_DIR/scripts/load-env.sh"

POSTGRES_DB="${KOR_TRAVEL_MAP_POSTGRES_DB:-kor_travel_map}"
POSTGRES_USER="${KOR_TRAVEL_MAP_POSTGRES_USER:-kor_travel_map}"
POSTGRES_PASSWORD="${KOR_TRAVEL_MAP_POSTGRES_PASSWORD:-kor_travel_map}"
DAGSTER_POSTGRES_DB="${KOR_TRAVEL_MAP_DAGSTER_POSTGRES_DB:-kor_travel_map_dagster}"

RESTORE_APP_DB="${KOR_TRAVEL_MAP_RESTORE_APP_DB:-${POSTGRES_DB}_restore}"
RESTORE_DAGSTER_DB="${KOR_TRAVEL_MAP_RESTORE_DAGSTER_DB:-${DAGSTER_POSTGRES_DB}_restore}"
RESTORE_RUSTFS_VOLUME="${KOR_TRAVEL_MAP_RESTORE_RUSTFS_VOLUME:-kor-travel-map-rustfs-restore}"
RESTORE_SWAP_ENV_FILE="${KOR_TRAVEL_MAP_RESTORE_SWAP_ENV_FILE:-$ROOT_DIR/.env.restore-swap}"
RESTORE_SWAP_APPLY="${KOR_TRAVEL_MAP_RESTORE_SWAP_APPLY:-0}"
RESTORE_SWAP_SKIP_VERIFY="${KOR_TRAVEL_MAP_RESTORE_SWAP_SKIP_VERIFY:-0}"

validate_identifier() {
  local value="$1"
  local label="$2"
  if [[ ! "$value" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "Invalid ${label}: ${value}" >&2
    exit 2
  fi
}

validate_volume_name() {
  local value="$1"
  local label="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9_.-]+$ ]]; then
    echo "Invalid ${label}: ${value}" >&2
    exit 2
  fi
}

select_python() {
  if [[ -n "${PYTHON_BIN:-}" ]]; then
    echo "$PYTHON_BIN"
  elif [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
    echo "$ROOT_DIR/.venv/bin/python"
  elif command -v python3 >/dev/null 2>&1; then
    command -v python3
  elif command -v python >/dev/null 2>&1; then
    command -v python
  else
    echo "required command not found: python3" >&2
    exit 127
  fi
}

with_maintenance_lock() {
  if [[ "${KOR_TRAVEL_MAP_MAINTENANCE_LOCK_HELD:-0}" == "1" || "${KOR_TRAVEL_MAP_MAINTENANCE_LOCK_DISABLED:-0}" == "1" ]]; then
    return 0
  fi
  local python_bin
  python_bin="$(select_python)"
  exec "$python_bin" "$ROOT_DIR/scripts/with-pg-advisory-lock.py" \
    --key "maintenance:backup-restore" \
    -- "$ROOT_DIR/scripts/docker-restore-swap.sh" "$@"
}

with_maintenance_lock "$@"

validate_identifier "$RESTORE_APP_DB" "restore app database"
validate_identifier "$RESTORE_DAGSTER_DB" "restore Dagster database"
validate_volume_name "$RESTORE_RUSTFS_VOLUME" "restore RustFS volume"

if [[ "$RESTORE_SWAP_SKIP_VERIFY" != "1" ]]; then
  KOR_TRAVEL_MAP_RESTORE_APP_DB="$RESTORE_APP_DB" \
    KOR_TRAVEL_MAP_RESTORE_DAGSTER_DB="$RESTORE_DAGSTER_DB" \
    KOR_TRAVEL_MAP_RESTORE_RUSTFS_VOLUME="$RESTORE_RUSTFS_VOLUME" \
    bash "$ROOT_DIR/scripts/docker-restore-verify.sh"
fi

SWAP_ENV_DIR="$(dirname "$RESTORE_SWAP_ENV_FILE")"
mkdir -p "$SWAP_ENV_DIR"
TMP_ENV_FILE="$(mktemp "${RESTORE_SWAP_ENV_FILE}.tmp.XXXXXX")"

cat >"$TMP_ENV_FILE" <<ENV
# Generated by scripts/docker-restore-swap.sh.
# Load this after .env to point standalone services at the verified restore set.
KOR_TRAVEL_MAP_DOCKER_PG_DSN=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${RESTORE_APP_DB}
KOR_TRAVEL_MAP_DOCKER_DAGSTER_PG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${RESTORE_DAGSTER_DB}
KOR_TRAVEL_MAP_RUSTFS_VOLUME=${RESTORE_RUSTFS_VOLUME}
ENV

mv "$TMP_ENV_FILE" "$RESTORE_SWAP_ENV_FILE"

if [[ "$RESTORE_SWAP_APPLY" == "1" ]]; then
  COMPOSE_COMMAND=(docker compose --env-file /dev/null)
  COMPOSE_COMMAND+=(--env-file "$RESTORE_SWAP_ENV_FILE")
  "${COMPOSE_COMMAND[@]}" up -d rustfs-perms rustfs rustfs-init api frontend dagster dagster-daemon
else
  cat <<SUMMARY
Restore swap env file generated:
  env_file=${RESTORE_SWAP_ENV_FILE}
  app_db=${RESTORE_APP_DB}
  dagster_db=${RESTORE_DAGSTER_DB}
  rustfs_volume=${RESTORE_RUSTFS_VOLUME}

Apply manually with:
  source scripts/load-env.sh
  docker compose --env-file /dev/null --env-file ${RESTORE_SWAP_ENV_FILE} up -d rustfs-perms rustfs rustfs-init api frontend dagster dagster-daemon
SUMMARY
fi
