#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${KOR_TRAVEL_MAP_ENV_FILE:-"$ROOT_DIR/.env"}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

export KOR_TRAVEL_MAP_ADMIN_HOST="${KOR_TRAVEL_MAP_ADMIN_HOST:-127.0.0.1}"
export KOR_TRAVEL_MAP_ADMIN_PORT="${KOR_TRAVEL_MAP_ADMIN_PORT:-12301}"
export KOR_TRAVEL_MAP_ADMIN_WEB_PORT="${KOR_TRAVEL_MAP_ADMIN_WEB_PORT:-12305}"
export KOR_TRAVEL_MAP_DAGSTER_PORT="${KOR_TRAVEL_MAP_DAGSTER_PORT:-12302}"
export KOR_TRAVEL_MAP_POSTGRES_HOST_PORT="${KOR_TRAVEL_MAP_POSTGRES_HOST_PORT:-5432}"
export KOR_TRAVEL_MAP_POSTGRES_DB="${KOR_TRAVEL_MAP_POSTGRES_DB:-kor_travel_map}"
export KOR_TRAVEL_MAP_POSTGRES_USER="${KOR_TRAVEL_MAP_POSTGRES_USER:-kor_travel_map}"
export KOR_TRAVEL_MAP_POSTGRES_PASSWORD="${KOR_TRAVEL_MAP_POSTGRES_PASSWORD:-kor_travel_map}"
export KOR_TRAVEL_MAP_RUSTFS_API_PORT="${KOR_TRAVEL_MAP_RUSTFS_API_PORT:-12101}"
export KOR_TRAVEL_MAP_RUSTFS_CONSOLE_PORT="${KOR_TRAVEL_MAP_RUSTFS_CONSOLE_PORT:-12105}"
export KOR_TRAVEL_MAP_DAGSTER_POSTGRES_DB="${KOR_TRAVEL_MAP_DAGSTER_POSTGRES_DB:-kor_travel_map_dagster}"
export KOR_TRAVEL_MAP_PG_DSN="${KOR_TRAVEL_MAP_PG_DSN:-postgresql+asyncpg://${KOR_TRAVEL_MAP_POSTGRES_USER}:${KOR_TRAVEL_MAP_POSTGRES_PASSWORD}@127.0.0.1:${KOR_TRAVEL_MAP_POSTGRES_HOST_PORT}/${KOR_TRAVEL_MAP_POSTGRES_DB}}"
export KOR_TRAVEL_MAP_PG_DSN_SYNC="${KOR_TRAVEL_MAP_PG_DSN_SYNC:-postgresql+psycopg://${KOR_TRAVEL_MAP_POSTGRES_USER}:${KOR_TRAVEL_MAP_POSTGRES_PASSWORD}@127.0.0.1:${KOR_TRAVEL_MAP_POSTGRES_HOST_PORT}/${KOR_TRAVEL_MAP_POSTGRES_DB}}"
export KOR_TRAVEL_MAP_DAGSTER_PG_URL="${KOR_TRAVEL_MAP_DAGSTER_PG_URL:-postgresql://${KOR_TRAVEL_MAP_POSTGRES_USER}:${KOR_TRAVEL_MAP_POSTGRES_PASSWORD}@127.0.0.1:${KOR_TRAVEL_MAP_POSTGRES_HOST_PORT}/${KOR_TRAVEL_MAP_DAGSTER_POSTGRES_DB}}"
export KOR_TRAVEL_MAP_DOCKER_DAGSTER_PG_URL="${KOR_TRAVEL_MAP_DOCKER_DAGSTER_PG_URL:-postgresql://${KOR_TRAVEL_MAP_POSTGRES_USER}:${KOR_TRAVEL_MAP_POSTGRES_PASSWORD}@postgres:5432/${KOR_TRAVEL_MAP_DAGSTER_POSTGRES_DB}}"

default_admin_cors_allow_origins() {
  local web_port="$KOR_TRAVEL_MAP_ADMIN_WEB_PORT"
  local origins=(
    "http://localhost:$web_port"
    "http://127.0.0.1:$web_port"
  )
  local wsl_ip="${KOR_TRAVEL_MAP_WSL_HOST_IP:-}"
  if [[ -z "$wsl_ip" ]] && [[ -n "${WSL_DISTRO_NAME:-}" ]] && command -v hostname >/dev/null 2>&1; then
    wsl_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  if [[ -n "$wsl_ip" ]]; then
    origins+=("http://$wsl_ip:$web_port")
  fi

  local json="["
  local origin
  for origin in "${origins[@]}"; do
    if [[ "$json" != "[" ]]; then
      json+=","
    fi
    json+="\"$origin\""
  done
  json+="]"
  printf '%s' "$json"
}

export KOR_TRAVEL_MAP_ADMIN_CORS_ALLOW_ORIGINS="${KOR_TRAVEL_MAP_ADMIN_CORS_ALLOW_ORIGINS:-$(default_admin_cors_allow_origins)}"
export KOR_TRAVEL_MAP_ADMIN_KOR_TRAVEL_GEO_BASE_URL="${KOR_TRAVEL_MAP_ADMIN_KOR_TRAVEL_GEO_BASE_URL:-http://127.0.0.1:12201}"
export KOR_TRAVEL_MAP_ADMIN_DAGSTER_URL="${KOR_TRAVEL_MAP_ADMIN_DAGSTER_URL:-http://127.0.0.1:${KOR_TRAVEL_MAP_DAGSTER_PORT}}"
export KOR_TRAVEL_MAP_ADMIN_DAGSTER_ALLOWED_HOSTS="${KOR_TRAVEL_MAP_ADMIN_DAGSTER_ALLOWED_HOSTS:-[\"127.0.0.1\",\"localhost\",\"::1\",\"dagster\"]}"
export KOR_TRAVEL_MAP_DOCKER_ADMIN_DAGSTER_URL="${KOR_TRAVEL_MAP_DOCKER_ADMIN_DAGSTER_URL:-http://dagster:${KOR_TRAVEL_MAP_DAGSTER_PORT}}"
export KOR_TRAVEL_MAP_DOCKER_ADMIN_DAGSTER_ALLOWED_HOSTS="${KOR_TRAVEL_MAP_DOCKER_ADMIN_DAGSTER_ALLOWED_HOSTS:-[\"dagster\",\"127.0.0.1\",\"localhost\",\"::1\"]}"
export KOR_TRAVEL_MAP_OBJECT_STORE_ENDPOINT_URL="${KOR_TRAVEL_MAP_OBJECT_STORE_ENDPOINT_URL:-http://127.0.0.1:${KOR_TRAVEL_MAP_RUSTFS_API_PORT}}"
export KOR_TRAVEL_MAP_OBJECT_STORE_BUCKET="${KOR_TRAVEL_MAP_OBJECT_STORE_BUCKET:-kor-travel-map}"
export KOR_TRAVEL_MAP_OBJECT_STORE_REGION="${KOR_TRAVEL_MAP_OBJECT_STORE_REGION:-us-east-1}"
export KOR_TRAVEL_MAP_OBJECT_STORE_ACCESS_KEY_ID="${KOR_TRAVEL_MAP_OBJECT_STORE_ACCESS_KEY_ID:-kor-travel-map-dev-access}"
export KOR_TRAVEL_MAP_OBJECT_STORE_SECRET_ACCESS_KEY="${KOR_TRAVEL_MAP_OBJECT_STORE_SECRET_ACCESS_KEY:-kor-travel-map-dev-secret}"
export KOR_TRAVEL_MAP_OBJECT_STORE_PUBLIC_BASE_URL="${KOR_TRAVEL_MAP_OBJECT_STORE_PUBLIC_BASE_URL:-http://127.0.0.1:${KOR_TRAVEL_MAP_RUSTFS_API_PORT}/${KOR_TRAVEL_MAP_OBJECT_STORE_BUCKET}}"
export KOR_TRAVEL_MAP_OBJECT_STORE_PREFIX="${KOR_TRAVEL_MAP_OBJECT_STORE_PREFIX:-features}"
export KOR_TRAVEL_MAP_OFFLINE_UPLOAD_BUCKET="${KOR_TRAVEL_MAP_OFFLINE_UPLOAD_BUCKET:-kor-travel-map-uploads}"
export KOR_TRAVEL_MAP_OFFLINE_UPLOAD_PREFIX="${KOR_TRAVEL_MAP_OFFLINE_UPLOAD_PREFIX:-offline-uploads}"
export KOR_TRAVEL_MAP_OFFLINE_UPLOAD_MAX_BYTES="${KOR_TRAVEL_MAP_OFFLINE_UPLOAD_MAX_BYTES:-104857600}"
export KOR_TRAVEL_MAP_DOCKER_OBJECT_STORE_ENDPOINT_URL="${KOR_TRAVEL_MAP_DOCKER_OBJECT_STORE_ENDPOINT_URL:-http://rustfs:9000}"
export DAGSTER_DISABLE_TELEMETRY="${DAGSTER_DISABLE_TELEMETRY:-yes}"
# docker build secret(github_token, #370) — 미설정이어도 compose가 unset env로
# 실패하지 않게 빈 값을 보장한다. private provider pin fetch 시에만 실 토큰 필요.
export GITHUB_TOKEN="${GITHUB_TOKEN:-}"
export NEXT_PUBLIC_KOR_TRAVEL_MAP_ADMIN_API="${NEXT_PUBLIC_KOR_TRAVEL_MAP_ADMIN_API:-http://127.0.0.1:${KOR_TRAVEL_MAP_ADMIN_PORT}}"
export NEXT_PUBLIC_KOR_TRAVEL_MAP_DAGSTER_URL="${NEXT_PUBLIC_KOR_TRAVEL_MAP_DAGSTER_URL:-http://127.0.0.1:${KOR_TRAVEL_MAP_DAGSTER_PORT}}"

export_first() {
  local target="$1"
  shift
  local current="${!target:-}"
  if [[ -n "$current" ]]; then
    export "$target=$current"
    return 0
  fi

  local name value
  for name in "$@"; do
    value="${!name:-}"
    if [[ -n "$value" ]]; then
      export "$target=$value"
      return 0
    fi
  done
}

export_first KOR_TRAVEL_MAP_DATA_GO_KR_SERVICE_KEY \
  DATA_GO_KR_SERVICE_KEY DATAGOKR_API_KEY PUBLIC_DATA_SERVICE_KEY SERVICE_KEY
export_first KOR_TRAVEL_MAP_OPINET_API_KEY \
  OPINET_API_KEY OPINET_SERVICE_KEY
export_first KOR_TRAVEL_MAP_KREX_EX_API_KEY \
  KEX_GO_API_KEY KREX_API_KEY KREX_SERVICE_KEY
export_first KOR_TRAVEL_MAP_KREX_GO_API_KEY \
  DATA_GO_KR_SERVICE_KEY KEX_GO_API_KEY KREX_API_KEY KREX_SERVICE_KEY

export_first KOR_TRAVEL_MAP_ADMIN_KMA_SERVICE_KEY \
  DATA_GO_KR_SERVICE_KEY KMA_SERVICE_KEY KMA_API_KEY PUBLIC_DATA_SERVICE_KEY SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_KMA_APIHUB_KEY \
  KMA_APIHUB_AUTH_KEY KMA_APIHUB_KEY
export_first KOR_TRAVEL_MAP_ADMIN_OPINET_SERVICE_KEY \
  OPINET_API_KEY OPINET_SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_DATAGOKR_SERVICE_KEY \
  DATA_GO_KR_SERVICE_KEY DATAGOKR_API_KEY PUBLIC_DATA_SERVICE_KEY SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_VISITKOREA_SERVICE_KEY \
  KTO_DATA_GO_KR_SERVICE_KEY VISITKOREA_SERVICE_KEY DATA_GO_KR_SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_KREX_SERVICE_KEY \
  KEX_GO_API_KEY KREX_API_KEY KREX_SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_KNPS_SERVICE_KEY \
  KNPS_SERVICE_KEY KNPS_API_KEY
export_first KOR_TRAVEL_MAP_ADMIN_AIRKOREA_SERVICE_KEY \
  AIRKOREA_SERVICE_KEY AIRKOREA_API_KEY DATA_GO_KR_SERVICE_KEY
export_first KOR_TRAVEL_MAP_ADMIN_KRFOREST_SERVICE_KEY \
  KRFOREST_SERVICE_KEY KRFOREST_API_KEY DATA_GO_KR_SERVICE_KEY
export_first NEXT_PUBLIC_VWORLD_API_KEY \
  KOR_TRAVEL_GEO_VWORLD_API_KEY VWORLD_API_KEY
