#!/usr/bin/env python3
"""고정된 restore swap env 파일을 안전하고 원자적으로 기록한다."""

from __future__ import annotations

import argparse
import os
import secrets
import stat
import sys
from collections.abc import Sequence
from contextlib import suppress
from pathlib import Path
from urllib.parse import quote

_FILENAME = ".env.restore-swap"


def _required_env(name: str) -> str:
    value = os.environ.get(name)
    if value is None:
        raise ValueError(f"{name} is required")
    if "\n" in value or "\r" in value or "\0" in value:
        raise ValueError(f"{name} contains a forbidden control character")
    return value


def _validate_existing(metadata: os.stat_result) -> None:
    if (
        not stat.S_ISREG(metadata.st_mode)
        or metadata.st_uid != os.geteuid()
        or stat.S_IMODE(metadata.st_mode) != 0o600
        or metadata.st_nlink != 1
    ):
        raise PermissionError("restore swap env file is not trusted")


def _write_all(file_fd: int, body: bytes) -> None:
    remaining = memoryview(body)
    while remaining:
        written = os.write(file_fd, remaining)
        if written <= 0:
            raise OSError("restore swap env write made no progress")
        remaining = remaining[written:]


def write_restore_swap_env(project_root: Path) -> Path:
    postgres_user = quote(
        _required_env("KOR_TRAVEL_MAP_POSTGRES_USER"),
        safe="",
    )
    postgres_password = quote(
        _required_env("KOR_TRAVEL_MAP_POSTGRES_PASSWORD"),
        safe="",
    )
    restore_app_db = quote(
        _required_env("KOR_TRAVEL_MAP_RESTORE_APP_DB"),
        safe="",
    )
    restore_dagster_db = quote(
        _required_env("KOR_TRAVEL_MAP_RESTORE_DAGSTER_DB"),
        safe="",
    )
    body = (
        "# Generated by scripts/write-restore-swap-env.py.\n"
        "# Load this after .env to point standalone services at the verified restore set.\n"
        "KOR_TRAVEL_MAP_DOCKER_PG_DSN=postgresql+asyncpg://"
        f"{postgres_user}:"
        f"{postgres_password}"
        "@postgres:5432/"
        f"{restore_app_db}\n"
        "KOR_TRAVEL_MAP_DOCKER_DAGSTER_PG_URL=postgresql://"
        f"{postgres_user}:"
        f"{postgres_password}"
        "@postgres:5432/"
        f"{restore_dagster_db}\n"
        "KOR_TRAVEL_MAP_RUSTFS_VOLUME="
        f"{_required_env('KOR_TRAVEL_MAP_RESTORE_RUSTFS_VOLUME')}\n"
    ).encode()
    root_fd = os.open(
        project_root,
        os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
    )
    root_metadata = os.fstat(root_fd)
    if (
        not stat.S_ISDIR(root_metadata.st_mode)
        or root_metadata.st_uid != os.geteuid()
        or stat.S_IMODE(root_metadata.st_mode) & 0o022
        or root_metadata.st_nlink < 2
    ):
        os.close(root_fd)
        raise PermissionError("restore swap project root is not trusted")
    temporary = f".restore-swap.{secrets.token_hex(16)}.tmp"
    file_fd: int | None = None
    try:
        try:
            existing = os.stat(
                _FILENAME,
                dir_fd=root_fd,
                follow_symlinks=False,
            )
        except FileNotFoundError:
            pass
        else:
            _validate_existing(existing)
        file_fd = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
            0o600,
            dir_fd=root_fd,
        )
        _validate_existing(os.fstat(file_fd))
        _write_all(file_fd, body)
        os.fsync(file_fd)
        os.close(file_fd)
        file_fd = None
        os.replace(
            temporary,
            _FILENAME,
            src_dir_fd=root_fd,
            dst_dir_fd=root_fd,
        )
        _validate_existing(
            os.stat(_FILENAME, dir_fd=root_fd, follow_symlinks=False)
        )
        os.fsync(root_fd)
    except BaseException:
        if file_fd is not None:
            os.close(file_fd)
        with suppress(FileNotFoundError):
            os.unlink(temporary, dir_fd=root_fd)
        raise
    finally:
        os.close(root_fd)
    return project_root / _FILENAME


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, required=True)
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)
    write_restore_swap_env(args.project_root)
    return os.EX_OK


if __name__ == "__main__":
    raise SystemExit(main())
