/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * public liveness probe
         * @description liveness — 의존 없이 항상 ``status='ok'`` 200. deep readiness는 후속.
         */
        get: operations["get_public_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PlaceCategory 정적 카탈로그(144건, 선택적 DB 분포) */
        get: operations["list_categories_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** feature 상세 batch 조회 (service read) */
        post: operations["get_features_batch_v1_features_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/in-bounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** bbox 안 feature 목록 (TripMate/public envelope) */
        get: operations["list_public_features_in_bounds_v1_features_in_bounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 좌표 중심 반경 주변 feature 목록 */
        get: operations["list_features_nearby_v1_features_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/nearby/by-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 외부 POI/cache target key 기준 주변 feature 목록 */
        get: operations["list_features_nearby_by_target_v1_features_nearby_by_target_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** feature 검색 (이름 trgm + bbox) */
        get: operations["search_public_features_v1_features_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** feature 단건 상세 */
        get: operations["get_feature_v1_features__feature_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/features/{feature_id}/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** feature weather card (forecast_style별 최신값 + freshness) */
        get: operations["get_feature_weather_v1_features__feature_id__weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전 provider 데이터 신선도 목록(대시보드)
         * @description 전 provider×dataset×scope의 last-sync/최근 실패 요약 (T-217g, D-07).
         *
         *     행 수가 유한(provider×dataset 수십 개)하므로 페이지네이션 없이 전량 반환한다
         *     (``/v1/categories`` bounded reference 패턴). 빈 환경은 200 + 빈 ``items``.
         */
        get: operations["list_providers_freshness_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{provider}/last-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** provider 데이터 신선도(last-sync) */
        get: operations["get_provider_last_sync_v1_providers__provider__last_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * public version
         * @description 배포 프로그램(admin)/메인 lib 버전 + commit(env ``KRTOUR_MAP_GIT_COMMIT``).
         */
        get: operations["get_public_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoriesData
         * @description ``GET /categories`` data payload.
         */
        CategoriesData: {
            /** Include Counts */
            include_counts: boolean;
            /** Items */
            items: components["schemas"]["CategorySummary"][];
        };
        /**
         * CategoriesResponse
         * @description ``GET /categories`` 응답.
         */
        CategoriesResponse: {
            data: components["schemas"]["CategoriesData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * CategorySummary
         * @description 정적 카탈로그 1건 (+ 선택적 DB 분포).
         */
        CategorySummary: {
            /** Code */
            code: string;
            /** Db Active */
            db_active?: boolean | null;
            /** Db Feature Count */
            db_feature_count?: number | null;
            /** Depth */
            depth: number;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
            /** Maki Icon */
            maki_icon: string;
            /** Parent Code */
            parent_code: string | null;
            /** Path */
            path: string[];
            /** Sort Order */
            sort_order: number;
            /** Tier1 Code */
            tier1_code: string;
            /** Tier1 Name */
            tier1_name: string;
            /** Tier2 Code */
            tier2_code: string;
            /** Tier2 Name */
            tier2_name: string | null;
            /** Tier3 Code */
            tier3_code: string;
            /** Tier3 Name */
            tier3_name: string | null;
            /** Tier4 Code */
            tier4_code: string;
            /** Tier4 Name */
            tier4_name: string | null;
        };
        /**
         * ClusterMeta
         * @description Map clustering metadata.
         */
        ClusterMeta: {
            /** Cluster Unit */
            cluster_unit?: string | null;
        };
        /**
         * ClusterSummary
         * @description 행정구역 rollup 클러스터 1건 (T-213c).
         */
        ClusterSummary: {
            /** Cluster Key */
            cluster_key: string;
            /** Feature Count */
            feature_count: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * FeatureBatchData
         * @description feature batch 상세 data payload.
         */
        FeatureBatchData: {
            /** Found */
            found: {
                [key: string]: components["schemas"]["FeatureDetailResponse"];
            };
            /** Missing */
            missing: string[];
        };
        /**
         * FeatureBatchRequest
         * @description feature batch 상세 조회 요청 (service read).
         */
        FeatureBatchRequest: {
            /** Feature Ids */
            feature_ids: string[];
        };
        /**
         * FeatureBatchResponse
         * @description ``POST /features/batch`` 응답.
         */
        FeatureBatchResponse: {
            data: components["schemas"]["FeatureBatchData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeatureDetailEnvelopeResponse
         * @description ``GET /features/{feature_id}`` public envelope 응답.
         */
        FeatureDetailEnvelopeResponse: {
            data: components["schemas"]["FeatureDetailResponse"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeatureDetailResponse
         * @description feature 단건 상세 data payload.
         */
        FeatureDetailResponse: {
            /** Address */
            address: {
                [key: string]: unknown;
            };
            /** Category */
            category: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Feature Id */
            feature_id: string;
            /** Kind */
            kind: string;
            /** Lat */
            lat?: number | null;
            /** Legal Dong Code */
            legal_dong_code?: string | null;
            /** Lon */
            lon?: number | null;
            /** Marker Color */
            marker_color?: string | null;
            /** Marker Icon */
            marker_icon?: string | null;
            /** Name */
            name: string;
            /** Sido Code */
            sido_code?: string | null;
            /** Sigungu Code */
            sigungu_code?: string | null;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Urls */
            urls: {
                [key: string]: unknown;
            };
        };
        /**
         * FeatureSearchData
         * @description 사용자 feature 검색 data payload.
         */
        FeatureSearchData: {
            /** Items */
            items: components["schemas"]["FeatureSummary"][];
        };
        /**
         * FeatureSearchResponse
         * @description ``GET /features/search`` 응답.
         */
        FeatureSearchResponse: {
            data: components["schemas"]["FeatureSearchData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeatureSummary
         * @description 지도/목록용 경량 feature 표현 (bbox 조회 결과 1건).
         */
        FeatureSummary: {
            /** Category */
            category: string;
            /** Feature Id */
            feature_id: string;
            /** Kind */
            kind: string;
            /**
             * Lat
             * @description 위도 (WGS84).
             */
            lat: number | null;
            /**
             * Lon
             * @description 경도 (WGS84). coord 없으면 null.
             */
            lon: number | null;
            /** Marker Color */
            marker_color?: string | null;
            /** Marker Icon */
            marker_icon?: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /**
         * FeatureWeatherResponse
         * @description ``GET /features/{feature_id}/weather`` 응답.
         */
        FeatureWeatherResponse: {
            data: components["schemas"]["WeatherCardData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeaturesInBoundsResponse
         * @description ``GET /features/in-bounds`` 응답.
         */
        FeaturesInBoundsResponse: {
            data: components["schemas"]["PublicFeatureListData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeaturesNearbyByTargetData
         * @description ``GET /features/nearby/by-target`` data payload.
         */
        FeaturesNearbyByTargetData: {
            /** Items */
            items: components["schemas"]["NearbyFeatureSummary"][];
            target: components["schemas"]["NearbyTargetSummary"];
        };
        /**
         * FeaturesNearbyByTargetResponse
         * @description ``GET /features/nearby/by-target`` 응답.
         */
        FeaturesNearbyByTargetResponse: {
            data: components["schemas"]["FeaturesNearbyByTargetData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * FeaturesNearbyData
         * @description ``GET /features/nearby`` data payload.
         */
        FeaturesNearbyData: {
            /** Items */
            items: components["schemas"]["NearbyFeatureSummary"][];
            origin: components["schemas"]["NearbyOriginSummary"];
        };
        /**
         * FeaturesNearbyResponse
         * @description ``GET /features/nearby`` 응답 (좌표 중심 반경).
         */
        FeaturesNearbyResponse: {
            data: components["schemas"]["FeaturesNearbyData"];
            meta: components["schemas"]["Meta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /**
         * Meta
         * @description 전 REST 표면에서 공유하는 성공 응답 metadata.
         */
        Meta: {
            cluster?: components["schemas"]["ClusterMeta"] | null;
            /** Duration Ms */
            duration_ms: number;
            page?: components["schemas"]["PageMeta"] | null;
            /**
             * Request Id
             * @description X-Request-ID와 같은 요청 ID.
             * @default
             */
            request_id: string;
        };
        /**
         * NearbyFeatureSummary
         * @description POI/cache target 주변 public feature summary.
         */
        NearbyFeatureSummary: {
            /** Category */
            category: string;
            /** Distance M */
            distance_m: number;
            /** Feature Id */
            feature_id: string;
            /** Kind */
            kind: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /**
         * NearbyOriginSummary
         * @description 좌표 기준 주변 조회 origin summary (입력 echo, T-213b).
         */
        NearbyOriginSummary: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m: number;
        };
        /**
         * NearbyTargetSummary
         * @description 주변 조회 기준 public target summary.
         */
        NearbyTargetSummary: {
            /** External System */
            external_system: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Target Key */
            target_key: string;
        };
        /**
         * PageMeta
         * @description Cursor pagination metadata.
         *
         *     ``next_cursor``는 페이지가 끝났을 때도 ``null``로 항상 직렬화한다.
         */
        PageMeta: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
            /** Total */
            total?: number | null;
        };
        /** ProviderLastSyncData */
        ProviderLastSyncData: {
            /** Items */
            items: components["schemas"]["SyncStateSummary"][];
            /** Provider */
            provider: string;
        };
        /**
         * ProviderLastSyncResponse
         * @description ``GET /providers/{provider}/last-sync`` 응답.
         */
        ProviderLastSyncResponse: {
            data: components["schemas"]["ProviderLastSyncData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * ProviderSyncStateSummary
         * @description 전체 목록의 1행 — ``SyncStateSummary`` + ``provider`` (cursor 제외).
         */
        ProviderSyncStateSummary: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Dataset Key */
            dataset_key: string;
            /** Last Failure At */
            last_failure_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Sync Scope */
            sync_scope: string;
        };
        /** ProvidersFreshnessData */
        ProvidersFreshnessData: {
            /** Items */
            items: components["schemas"]["ProviderSyncStateSummary"][];
        };
        /**
         * ProvidersFreshnessResponse
         * @description ``GET /providers`` 응답 — 전 provider×dataset 신선도 목록.
         */
        ProvidersFreshnessResponse: {
            data: components["schemas"]["ProvidersFreshnessData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * PublicFeatureListData
         * @description public feature 목록 data payload.
         *
         *     ``cluster_unit``이 None이면 ``items``(개별 feature), 아니면 ``clusters``
         *     (행정구역 rollup)를 채운다(T-213c).
         */
        PublicFeatureListData: {
            /**
             * Clusters
             * @default []
             */
            clusters: components["schemas"]["ClusterSummary"][];
            /** Items */
            items: components["schemas"]["FeatureSummary"][];
        };
        /**
         * PublicHealthResponse
         * @description ``GET /health`` 응답 (liveness).
         */
        PublicHealthResponse: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * PublicVersionResponse
         * @description ``GET /version`` 응답.
         */
        PublicVersionResponse: {
            data: components["schemas"]["VersionData"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * SyncStateSummary
         * @description provider 1 (dataset_key, sync_scope) 신선도 — cursor 제외.
         */
        SyncStateSummary: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Dataset Key */
            dataset_key: string;
            /** Last Failure At */
            last_failure_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Status */
            status: string;
            /** Sync Scope */
            sync_scope: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionData */
        VersionData: {
            /** Commit */
            commit?: string | null;
            /** Krtour Map Version */
            krtour_map_version: string;
            /** Openapi Version */
            openapi_version: string;
            /** Version */
            version: string;
        };
        /**
         * WeatherCardData
         * @description ``GET /features/{feature_id}/weather`` data payload.
         */
        WeatherCardData: {
            /** Asof */
            asof?: string | null;
            /** Feature Id */
            feature_id: string;
            /** Is Stale */
            is_stale: boolean;
            /** Latest At */
            latest_at?: string | null;
            /** Metrics */
            metrics: components["schemas"]["WeatherMetricOut"][];
            /** Source Styles */
            source_styles: string[];
        };
        /**
         * WeatherMetricOut
         * @description weather card metric 1건 (forecast_style × metric_key 최신값, T-213e).
         */
        WeatherMetricOut: {
            /** Forecast Style */
            forecast_style: string;
            /** Issued At */
            issued_at?: string | null;
            /** Metric Key */
            metric_key: string;
            /** Metric Name */
            metric_name?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Severity */
            severity?: string | null;
            /** Timeline Bucket */
            timeline_bucket?: string | null;
            /** Unit */
            unit?: string | null;
            /** Valid At */
            valid_at?: string | null;
            /** Value Number */
            value_number?: number | null;
            /** Value Text */
            value_text?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_public_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicHealthResponse"];
                };
            };
        };
    };
    list_categories_v1_categories_get: {
        parameters: {
            query?: {
                /** @description 현재 DB feature 분포(category별 수)를 포함 */
                include_counts?: boolean;
                /** @description counts를 status='active' feature만으로 집계 */
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_batch_v1_features_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureBatchResponse"];
                };
            };
            /** @description feature_ids 1~200개 필요 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_public_features_in_bounds_v1_features_in_bounds_get: {
        parameters: {
            query: {
                /** @description bbox 최소 경도 (WGS84). */
                min_lon: number;
                /** @description bbox 최소 위도. */
                min_lat: number;
                /** @description bbox 최대 경도. */
                max_lon: number;
                /** @description bbox 최대 위도. */
                max_lat: number;
                /** @description feature kind 반복 필터. */
                kind?: string[] | null;
                /** @description category code 반복 필터. */
                category?: string[] | null;
                zoom?: number | null;
                /** @description 행정구역 rollup 단위. 미지정 시 zoom으로 유도. */
                cluster_unit?: ("sido" | "sigungu" | "eupmyeondong") | null;
                max_items?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesInBoundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_features_nearby_v1_features_nearby_get: {
        parameters: {
            query: {
                /** @description 중심 경도(4326). */
                lon: number;
                /** @description 중심 위도(4326). */
                lat: number;
                /** @description 반경(m). 최대 100km. */
                radius_m: number;
                /** @description feature kind 반복 필터. */
                kind?: string[] | null;
                /** @description category code 반복 필터. */
                category?: string[] | null;
                /** @description feature status 반복 필터. 기본 active. */
                status?: string[] | null;
                /** @description primary provider 반복 필터. */
                provider?: string[] | null;
                page_size?: number;
                cursor?: string | null;
                sort?: "distance" | "name" | "last_updated_at";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesNearbyResponse"];
                };
            };
            /** @description cursor/sort/radius/좌표 오류 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_features_nearby_by_target_v1_features_nearby_by_target_get: {
        parameters: {
            query: {
                /** @description 외부 시스템 이름. 예: tripmate */
                external_system: string;
                /** @description 외부 POI 고유 key. */
                target_key: string;
                /** @description 미지정 시 target 기본 radius 사용. */
                radius_km?: number | null;
                /** @description feature kind 반복 필터. */
                kind?: string[] | null;
                /** @description category code 반복 필터. */
                category?: string[] | null;
                /** @description feature status 반복 필터. 기본 active. */
                status?: string[] | null;
                /** @description primary provider 반복 필터. */
                provider?: string[] | null;
                page_size?: number;
                cursor?: string | null;
                sort?: "distance" | "name" | "last_updated_at";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesNearbyByTargetResponse"];
                };
            };
            /** @description target 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description cursor/sort/radius 오류 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_public_features_v1_features_search_get: {
        parameters: {
            query?: {
                /** @description name pg_trgm 검색어. */
                q?: string | null;
                /** @description feature kind 반복 필터. */
                kind?: string[] | null;
                /** @description category code 반복 필터. */
                category?: string[] | null;
                /** @description bbox 최소 경도 (WGS84). */
                min_lon?: number | null;
                /** @description bbox 최소 위도. */
                min_lat?: number | null;
                /** @description bbox 최대 경도. */
                max_lon?: number | null;
                /** @description bbox 최대 위도. */
                max_lat?: number | null;
                /** @description 페이지 크기. */
                page_size?: number;
                cursor?: string | null;
                include_total?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSearchResponse"];
                };
            };
            /** @description 검색 범위 또는 cursor 오류 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_feature_v1_features__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureDetailEnvelopeResponse"];
                };
            };
            /** @description feature_id 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_weather_v1_features__feature_id__weather_get: {
        parameters: {
            query?: {
                /** @description 이 시점 이하 weather만(미래 예보 제외). */
                asof?: string | null;
            };
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureWeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_freshness_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersFreshnessResponse"];
                };
            };
        };
    };
    get_provider_last_sync_v1_providers__provider__last_sync_get: {
        parameters: {
            query?: {
                /** @description dataset_key 필터 */
                dataset_key?: string | null;
                /** @description sync_scope 필터 */
                sync_scope?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderLastSyncResponse"];
                };
            };
            /** @description provider sync state 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicVersionResponse"];
                };
            };
        };
    };
}
